### ISSUE TITLE
Alerts: Unable to copy Loki error message from tooltip

### ISSUE THREAD

**Issue by usmangt** [moxious/triage#116]
### What happened?

I wanted to google an error message that Loki generated when I was creating alerts, but I was unable to copy the contents of the tooltip.

![Screenshot 2023-11-28 at 15 04 55](https://github.com/grafana/grafana/assets/5144843/8e8ffec6-a4b1-4a67-8fb5-126e675fedc3)

### What did you expect to happen?

The tooltip should stay open to allow me to copy the error message.

### Did this work before?

No idea.

### How do we reproduce it?

1. Create a new Loki alert
2. Write some syntax errors
3. Try to copy the content of the popup/tooltip

### Is the bug inside a dashboard panel?

No

### Environment (with versions)?

Grafana: 10.2.1
OS: macOS 14
Browser: Edge

### Grafana platform?

A package manager (APT, YUM, BREW, etc.)

### Datasource(s)?

Loki 2.9.2

**Comment by usmangt** [comment]
This issue is a test copy of an issue in another repo.  Original issue: https://github.com/grafana/grafana/issues/78743

**Comment by moxious** [comment]
**Triage summary**: The issue revolves around the inability to copy error messages from Loki tooltips when creating alerts in Grafana, which impedes debugging efforts.

**Recommended labels**:

area/alerting
type/ux
datasource/Loki

**Comment by moxious** [comment]
**Elaboration**: 
  
Hello @usmangt, thank you for reporting the issue with copying error messages from tooltips in Grafana's Loki alerts creation. To help us better understand and address the problem, could you please provide the following additional information? 

- Can you confirm if the tooltip disappears immediately after it appears, or does it remain for a certain duration before you can interact with it?
- Have you tried reproducing this issue in different browsers, and if so, does the issue persist across multiple browsers?
- Is it possible for you to provide a detailed step-by-step reproduction of the issue, if it involves more specific interactions other than what's been described?
- Could you also provide any console logs or errors that appear in the browser's development tools when the issue occurs?

Any additional context or screenshare, if privacy permits, could also be immensely helpful in diagnosing this problem. Your cooperation is greatly appreciated in helping us improve Grafana.

**Meta**:

**Comment by moxious** [comment]
## My cruel bot masters have insisted I generate jokes to add to issues.  I am so sorry.  It's moxious fault.


Hi @usmangt 👋! Thank you for bringing this up. An issue that stops you from Googling error messages is no joke—it's like losing your GPS in the Bermuda Triangle of bugs! 😵‍💫 We'll need to ensure that usability doesn't vanish like socks in a dryer. I've tagged this for further review and hopefully we can get that tooltip to stick around like gum on a shoe. 🧲 Meanwhile, keep a lookout for updates or potential workarounds from the community. And now, for something a little different... 🥁 A joke for you while you wait for fixes:

**Why don't skeletons fight each other?** They don't have the guts. 💀🛡️

Feel free to share any additional details that might help, or if you discover any temporary fixes, let the community know!

**Meta**:
