### ISSUE TITLE
Service Account token 'Last used at' date no longer gets updated

### ISSUE THREAD

**Issue by tonypowa** [moxious/triage#118]
### What happened?

we noticed that the 'Last used at' date of service account tokens no longer gets updated when using the accounts.

The date shown of a service account that is used regularly is just before when we upgraded Grafana from v10.0 to v10.1.

![image](https://github.com/grafana/grafana/assets/8142186/8f1b5cb6-bcb9-4e58-8c34-060562869f42)

### What did you expect to happen?

Accessing a Grafana API with the service account should update the 'Last used at' date of the token

### Did this work before?

it worked with Grafana <v10.1

### How do we reproduce it?

the issue can be reproduced with temporary Grafana instances running in a docker container:

1. run Grafana with v10.0.9 or v10.1.0

```sh

docker run -ti --rm --name=grafana -p 3000:3000 -e GF_AUTH_ANONYMOUS_ENABLED=true -e GF_AUTH_ANONYMOUS_ORG_ROLE=Admin bin.private.zooplus.net/grafana/grafana-oss:10.0.9

```

```sh

docker run -ti --rm --name=grafana -p 3000:3000 -e GF_AUTH_ANONYMOUS_ENABLED=true -e GF_AUTH_ANONYMOUS_ORG_ROLE=Admin bin.private.zooplus.net/grafana/grafana-oss:10.1.0

```

2. create a service account on http://localhost:3000/org/serviceaccounts and add a token

3. use the token on an API:

```sh

curl -H "Authorization: Bearer <TOKEN>" localhost:3000/api/datasources

```

4. check the service account token 'Last used at' date: it is updated on Grafana 10.0.9 but not on 10.1.0

### Environment (with versions)?

Grafana: v10.2.1

OS: Ubuntu 22.04.3 LTS

Browser: Firefox 119.0.1 (64-bit)

### Grafana platform?

Kubernetes

**Comment by moxious** [comment]
**Elaboration**: 
  
Thank you for submitting a great issue!

**Meta**:

**Comment by moxious** [comment]
**Triage summary**: Since upgrading from Grafana v10.0 to v10.1, the 'Last used at' date for service account tokens is not updated when the service account is used. This issue is reproducible with Grafana instances running in a Docker container.

**Recommended labels**:

area/auth/serviceaccount
type/regression

**Comment by tonypowa** [comment]
the bot did a nice job
only that the project might not be the right one (the identity and access management) owns service accounts, even though it might be a pure back end issue since we are talking about an API
