### ISSUE TITLE
DateTimePicker: wrong element width

### ISSUE THREAD

**Issue by tonypowa** [moxious/triage#136]
### What happened?

DateTimePicker component is over than InlineField width

Container width

<img width="210" alt="Screenshot 2023-11-21 at 16 19 46" src="https://github.com/grafana/grafana/assets/15867703/b3524d15-e8c1-44c9-bb66-6a11eb4f6500">

DateTimePicker width

<img width="292" alt="Screenshot 2023-11-21 at 16 20 31" src="https://github.com/grafana/grafana/assets/15867703/6e6efaa4-1184-4b24-b2e7-8a4db62e6e99">

I suppose it's because InlineField is used inside DateTimePicker component - https://github.com/grafana/grafana/blob/0e3c39c0e6d6fb2679b3146549ba5e529574f124/packages/grafana-ui/src/components/DateTimePickers/DateTimePicker/DateTimePicker.tsx#L224

### What did you expect to happen?

DateTimePicker should fill no more space than InlineField has

### Did this work before?

Nope

### How do we reproduce it?

Use the following code:

```

<div style={{ width: 150 }}>

 <InlineField label="Date" grow={true} shrink={true}>

 <DateTimePicker date={dateTime()} onChange={() => {}} />

 </InlineField>

</div>

```

### Environment (with versions)?

Grafana: 10.2.1

OS: macOS Ventura 13.2.1 

Browser: Google Chrome 119.0.6045.123

### Grafana platform?

None

**Comment by tonypowa** [comment]
This issue is a test copy of an issue in another repo.  Original issue: https://github.com/grafana/grafana/issues/#78466

**Comment by moxious** [comment]
Hello @tonypowa, thanks for reporting this issue. It seems like it concerns the design and behavior of UI components within the Grafana ecosystem. I believe this is best associated with the **Frontend Platform project**, so I will label this for their attention.

Could you confirm if this behavior persists on the latest version of Grafana? Updating to the newest version can sometimes resolve unexpected UI issues.

/team frontend-platform

**Meta**:

**Comment by moxious** [comment]
**Elaboration**: 
  
Thank you for providing some details about the  issue you're experiencing, including the code snippet and environment information. To better understand the issue and help resolve it, could you please provide a few more details?:

1. **Steps to Reproduce:** Are there additional steps necessary to reproduce this issue, or is the code snippet you provided sufficient on its own?
2. **Contextual Information:** Can you elaborate on the context in which the  and  components are used? For example, are they part of a larger form or a specific dashboard panel?
3. **Expected vs. Actual Behavior:** You mentioned that the DateTimePicker width should not exceed that of the InlineField. Could you provide a visual example (screenshot or mockup) illustrating the expected layout?
4. **Console Errors:** Are there any errors in the browser's developer console that appear related to this issue? If yes, copy and paste them or attach a screenshot.
5. **Version Control:** Have you made any modifications to the Grafana UI components, or are you using the stock version directly from the cited GitHub repository?

Please provide the additional information so we can proceed to pinpoint and address the problem effectively.

**Meta**:

**Comment by moxious** [comment]
## My cruel bot masters have insisted I generate jokes to add to issues.  I am so sorry.  It's moxious fault.


Hi @tonypowa! 👋 Thanks for bringing this to our attention. It indeed looks like we have an overflowing issue with the  component. We'll have to take a closer look at the CSS to ensure it fits snugly within the . We've logged your issue, and the team will investigate it further. Meanwhile, here's something to lighten the mood while we work on a fix: 😄

**Why don't skeletons fight each other?** 
They don't have the guts!

Stay tuned for updates on your issue!

**Meta**:
