### ISSUE TITLE
Logs Dashboard: Default display of the first 1000 characters when log lines are too long

### ISSUE THREAD

**Issue by tonypowa** [moxious/triage#155]
**Why is this needed**:

When log line is too long(like Java error log contains stack), showing all content by default will not be a good user experience.

**What would you like to be added**:

Display first of 1000 characters if log lines are too long, and give a toggle switch button to show full lines as if user want to watch the original full lines. The effect is as follows:

![image](https://github.com/grafana/grafana/assets/4892550/c29e8816-f767-4522-bc00-1fb08473005c)

**Who is this feature for?**

Logs panel users

**Comment by tonypowa** [comment]
This issue is a test copy of an issue in another repo.  Original issue: https://github.com/grafana/grafana/issues/#78572

**Comment by moxious** [comment]
## My cruel bot masters have insisted I generate jokes to add to issues.  I am so sorry.  It's moxious fault.


Hi @tonypowa! 📘 First off, thanks for submitting this feature request. It definitely sounds like a smart move to avoid information overload by limiting the initial display of lengthy log lines. Your idea of a toggle switch to expand the content is quite intuitive! 👍 We'll bring this up in our next discussion to see how it could potentially be integrated into the UI without compromising on overall usability or performance. Stay tuned! 🚀 Oh, and while we're sifting through logs, here's something to lighten the mood:

**Joke Time:** 
Why don't programmers like nature? It has too many bugs! 🐞😂

Let's keep our code and logs cleaner than Mother Nature! Keep the feedback coming! 🌟

**Meta**:

**Comment by moxious** [comment]
**Triage summary**: The feature request is to enhance the Logs Dashboard by displaying only the first 1000 characters of a log line when it is too long, with a toggle option provided to view the entire log line if desired. This aims to improve user experience by avoiding the default display of overly lengthy logs, such as verbose Java error stacks.

**Recommended labels**:

area/logs
type/feature-request

**Comment by moxious** [comment]
Hi @tonypowa, thanks for the feature request! It sounds like this would be relevant to the **Observability Logs Project**, which focuses on enhancing the user experience with logs in Grafana. I'll tag this issue for their attention. Meanwhile, if you have any prototype or code suggestions, feel free to share them to help in assessing your proposal.

/cc @grafana-logs-team

**Meta**:

**Comment by moxious** [comment]
**Elaboration**: 
  
Thank you for submitting this feature request! Your suggestion to improve the Logs Dashboard by displaying the first 1000 characters of overly long log lines sounds like a reasonable way to enhance user experience.

Could you please provide a bit more detail to help us assess the implementation of this feature:

1. **Current Behavior**: What is the current behavior of the dashboard when displaying long log lines? Are they truncated, wrapped, or do they cause any performance issues?

2. **Threshold Clarification**: Is the 1000-character threshold fixed, or should it be configurable by the user/administrator? If configurable, which default value do you propose?

3. **User Interaction**: When toggling to view the full lines, would you prefer the expansion to happen in place, or would you rather have the log line open in a separate pop-up or overlay?

4. **Loading Implications**: Have you considered how the system will handle loading the full content upon user request? For instance, are there concerns about loading times or memory usage?

5. **Accessibility Considerations**: How do you envision this feature accommodating users who rely on screen readers or other accessibility tools?

We appreciate your input, and it will be essential in designing a solution that fits the needs of all Logs Dashboard users.

Additionally, if you have any technical specifications or examples of similar implementations in other systems that you find effective, please share them as they could help inform the direction of this feature.

Look forward to your response!

**Meta**:
