### ISSUE TITLE
Force transition to "Main" when requesting /api/datasources in any other organization.

### ISSUE THREAD

**Issue by tonypowa** [moxious/triage#160]
### What happened?

Unexpected behavior with API request "/api/datasources".

### What did you expect to happen?

Retrieving JSON with the parameters of the current organization's datasources, not the datasources in "Main".

### Did this work before?

Yes, it appeared after migrating from 10.0.3 to 10.2.1.

Before migrating to 10.2.1, the combination of the post method with switching organizations "/api/user/using/$some_orgid" and get with a request for all local data sources "/api/datasources" worked.

### How do we reproduce it?

1. Make post request for switch to some different from "Main" organization "/api/user/using/$some_orgid".

2. Make get request and get all datasources in organization "/api/datasources".

3. Get unexpected datasources from the "Main" organization and switch to it.

### Is the bug inside a dashboard panel?

Nope

### Environment (with versions)?

Grafana: 10.2.1

OS: Ubuntu 18.04

Browser: python3 (requests lib)

### Grafana platform?

A package manager (APT, YUM, BREW, etc.)

### Datasource(s)?

"Zabbix plugin for Grafana" - https://grafana.com/grafana/plugins/alexanderzobnin-zabbix-app/

**Comment by tonypowa** [comment]
This issue is a test copy of an issue in another repo.  Original issue: https://github.com/grafana/grafana/issues/#78648

**Comment by moxious** [comment]
**Triage summary**: After upgrading Grafana from 10.0.3 to 10.2.1, the API request  unexpectedly returns datasources from the 'Main' organization, even after switching to a different organization via . This behavior changed post-upgrade and needs investigation.

**Recommended labels**:

area/backend/api
area/datasource
type/regression
datasource/Zabbix

**Comment by moxious** [comment]
**Elaboration**: 
  
Thank you for the detailed report, tonypowa! It certainly helps us get a good starting point on the issue at hand. To best address your problem with the API transition behavior after upgrading Grafana, I have some follow-up questions that would help us pinpoint the issue further:

1. Could you please confirm if there are any error messages in the Grafana server logs when you experience the unexpected behavior?

2. Is it possible to provide a code snippet of the script making the API calls? This would help us understand if there’s any potential issue at the client level.

3. Have there been any changes to the API in the release notes of Grafana 10.2.1 that may relate to the issue observed?

4. Have you tried reproducing this issue on a fresh install of Grafana 10.2.1 without any of the data from 10.0.3 to verify if the problem persists in a clean environment?

5. After the switch to a different organization fails and redirects you to the 'Main' organization, do subsequent API requests continue to redirect to 'Main', or does only the first request after the organization switch gets affected?

6. Can you confirm if the behavior is consistently reproducible or if it occurs intermittently?

Once we have this additional information, it will help us better understand and hopefully resolve the issue more efficiently. Look forward to your response!

**Comment by moxious** [comment]
Hi @tonypowa, it sounds like this issue might be related to a regression in the Grafana backend API, particularly with the way it handles organization-specific datasource requests. This seems like a critical use-case for Grafana installations with multiple organizations set up. 

Based on the information provided and the labels attached to the issue (area/backend/api, area/datasource), I recommend forwarding this issue to the **Backend Platform Project** as they are likely best equipped to address API and datasource integration regressions.

The team can investigate changes between versions 10.0.3 and 10.2.1 that might have caused this regression. In the meantime, if there is a temporary workaround, it would be greatly appreciated if you could share it with the community.

**Meta**:

**Comment by tonypowa** [comment]
id' move it more to the Identity team but nice elaboration points
