### ISSUE TITLE
Provisioning: Azure SQLMI Datasource can't be configured to use Azure Authentication

### ISSUE THREAD

**Issue by usmangt** [moxious/triage#165]
### What happened?

I'm trying to provision a connection to an Azure SQL Managed Instance as a Grafana datasource from a YAML file to avoid having it tweakable in the UI by users. I have confirmed that the provided URL, tenant, client, and secret work correctly from the datasource management page in the Grafana UI when logged in as admin. Using the same tenant/client/secret/URI in the jsonData field of a datasource.yml file does not work. The syntax for doing this in a provisioning file is undocumented so I've been looking at the Go source code in grafana/pkg/tsdb/mssql/mssql.go and trying to guess at correct variable names/capitalization, since the variable names in Go source do not correspond exactly to expected JSON values.

### What did you expect to happen?

I expected to provision a SQLMI data source.

### Did this work before?

no

### How do we reproduce it?

```
$ cat <<EOF > /etc/grafana/provisioning/datasources/datasource.yaml
apiVersion: 1
datasources:
 - name: SQLMI
 type: mssql
 url: censored.whoops.nope.database.windows.net:1433
 jsonData:
 database: Foo
 authenticationType: "AzureAuthentication"
 azureAuthType: "clientsecret"
 tenantId: "asd;flkasjdf;laksfja;sdl"
 clientId: "asdfa;lsdfj;asdlkja;sdfkja;sfkl"
 encrypt: 'true'
 secureJsonData:
 clientSecret: "ads;fkj;sdlkfj;asldfja;sdfklj"
EOF
```

### Is the bug inside a dashboard panel?

no

### Environment (with versions)?

Grafana: 10.2.2
OS: Win10
Browser: MS Edge

### Grafana platform?

Kubernetes

### Datasource(s)?

MSSQL

**Comment by usmangt** [comment]
This issue is a test copy of an issue in another repo.  Original issue: https://github.com/grafana/grafana/issues/78711

**Comment by moxious** [comment]
@support-agent Do we have similiar issues already?

**Comment by moxious** [comment]
**Triage summary**: Azure SQL Managed Instance datasource provisioning via YAML file fails when attempting to use Azure Authentication, as the necessary configuration syntax is not documented and cannot be inferred from the source code.

**Recommended labels**:

area/datasource
type/feature-request
datasource/MSSQL

**Comment by moxious** [comment]
Hello @usmangt, it seems like your issue is related to the **AWS Datasources project**, as it involves provisioning a datasource specifically for Azure SQL Managed Instance which falls under the category of cloud data sources that the AWS Datasources team often handles. I would recommend transferring this issue to their attention for further assistance.
