### ISSUE TITLE
Alerts: Unable to copy error message from tooltip

### ISSUE THREAD

**Issue by tonypowa** [moxious/triage#167]
### What happened?

I wanted to google an error message that an alert query generated, but I was unable to copy the contents of the tooltip.

![Screenshot 2023-11-28 at 15 04 55](https://github.com/grafana/grafana/assets/5144843/8e8ffec6-a4b1-4a67-8fb5-126e675fedc3)

### What did you expect to happen?

The tooltip should stay open to allow me to copy the error message.

### Did this work before?

No idea.

### How do we reproduce it?

1. Create a new alert

2. Write some syntax errors

3. Try to copy the content of the error popup/tooltip

### Is the bug inside a dashboard panel?

No

### Environment (with versions)?

Grafana: 10.2.1

OS: macOS 14

Browser: Edge

### Grafana platform?

A package manager (APT, YUM, BREW, etc.)

### Datasource(s)?

Loki 2.9.2

**Comment by tonypowa** [comment]
This issue is a test copy of an issue in another repo.  Original issue: https://github.com/grafana/grafana/issues/#78743

**Comment by moxious** [comment]
@support-agent Do we have similiar issues already?

**Comment by moxious** [comment]
Thanks @tonypowa for the report! This issue seems related to the user interface components specific to alerts in the Grafana UI, hence I believe it should be directed towards the **Alerting project**. I'll tag this issue for that team to take a look and they can evaluate the tooltip behavior regarding error messages in alerts.

```yaml
/project Alerting project
```

**Comment by moxious** [comment]
**Elaboration**:


Thank you for providing details on the issue you encountered with tooltips in Grafana. To better assist you and address this issue, we'd need just a bit more information: 

1. Could you confirm if the tooltip disappears immediately or if it stays open for a short period of time before closing?
2. Is the behavior consistent across different browsers or have you noticed it only in Edge?
3. Are you able to interact with other tooltips in Grafana without issues (i.e., they stay open, and you can copy content from them)?
4. Have you tried any workarounds, like inspecting the page element through the browser's developer tools to copy the tooltip content from there?
5. Can you provide a short video or a better-quality screenshot showing the problem? The link you've posted seems broken and we are unable to view the screenshot.
6. Would you be able to supply any error logs that appear in the Grafana server log or the browser console when you encounter this issue?

Any additional information you can provide will help us better understand the problem and work towards a resolution. Thank you!

**Comment by moxious** [comment]
**Triage summary**: User is unable to copy the content of a tooltip displaying an error message generated by an alert query in Grafana. They expect the tooltip to remain open to allow for copying the error details.

**Recommended labels**:

area/alerting
type/ux
type/feature-request
