### ISSUE TITLE
Product Area: UI/UX Elasticsearch 5.0.0 plugin

### ISSUE THREAD

**Issue by tonypowa** [moxious/triage#169]
### What happened?

Highlighting is not working in elasticsearch datasource in EXPLORE view

In the previous version of Grafana, with which we updated, the highlight worked correctly in any fields

![Untitled22](https://github.com/grafana/grafana/assets/48260560/50db6db9-f15f-4fbb-bb4b-5bad6f46b4b0)

Also, log information from the _source field has stopped being displayed. Although all the information in the datasource is filled out correctly. All these problems arose after updating Grafana. There weren't any before.

![Untitled3](https://github.com/grafana/grafana/assets/48260560/172bb45c-6c30-418d-84ec-ff8772b9aa8f)

### What did you expect to happen?

Working highliting

### Did this work before?

Upgrade grafana from 10.0.3 to v10.2.1

### How do we reproduce it?

1. Install grafana 10.0.3 from deb

2. Install elasticsearch datasource 5.0.0

3. Upgrade grafana to 10.2.1

4. => Bug in Explore (logs) with highlighting and display info

### Environment (with versions)?

Grafana: v10.2.1 (533a733e4eda44041e43358c5a51203e9b42c9ea)

OS: Ubuntu 22.04.3 LTS

Browser: 119.0.6045.161 Chrome

### Grafana platform?

A package manager (APT, YUM, BREW, etc.)

### Datasource(s)?

Elasticsearch 5.0.0

**Comment by tonypowa** [comment]
This issue is a test copy of an issue in another repo.  Original issue: https://github.com/grafana/grafana/issues/#78790

**Comment by moxious** [comment]
@support-agent Do we have similiar issues already?

**Comment by moxious** [comment]
**Triage summary**: After upgrading Grafana from 10.0.3 to 10.2.1, users are experiencing issues with highlighting and information display in the Elasticsearch 5.0.0 datasource Explore view.

**Recommended labels**:

area/explore
datasource/Elasticsearch
type/regression
type/bug

**Comment by moxious** [comment]
Hi @tonypowa, it appears you're experiencing issues with Elasticsearch datasource plugin in Grafana. I'm transferring this issue to the **Plugins Platform** project, where the team specializes in datasource plugins and their respective issues, including highlighting and data display functionality within Grafana's EXPLORE feature.

**Comment by moxious** [comment]
**Elaboration**:


Thank you for bringing this issue to our attention, and for providing an outline of the problem you are facing with the Elasticsearch datasource in Grafana's EXPLORE view. To help us better understand and address the issue, I have a few additional questions and requests for information that would be very helpful for our investigation:

1. Could you please provide the specific queries you are using when you notice the highlighting problem? This could be critical in reproducing the issue.
2. Can you confirm if there were any other changes aside from the Grafana upgrade? For example, changes in Elasticsearch version, other related plugins, or any system-level updates?
3. Are there any error messages in the Grafana server logs or in the browser console when you try to use highlighting or access the _source field logs? If so, could you please share those?
4. It appears the links to the screenshots you provided are not accessible. Could you verify the links to the screenshots of the issue or upload the images again?
5. When you say 'log information from the _source field has stopped being displayed', could you clarify if this impacts all logs or particular entries? Is there a pattern you've noticed?

Providing this additional context will help us replicate the conditions closely and troubleshoot the problem effectively. 

Thanks again for your report, and we look forward to your response!
