### ISSUE TITLE
TimeSeries: Wrong Data display after adjusting the time range 

### ISSUE THREAD

**Issue by tonypowa** [moxious/triage#171]
### What happened?

![01](https://github.com/grafana/grafana/assets/141797260/01f03a73-7e93-4763-b777-cee35a2c6524)

### What did you expect to happen?

The value should be show 60 not 160

![02](https://github.com/grafana/grafana/assets/141797260/0fed51f6-b121-42c2-9a5d-2fe270bd03dd)

### Did this work before?

not yet

### How do we reproduce it?

Enlarge the time interval for a certain value

![image](https://github.com/grafana/grafana/assets/141797260/575c0241-1e50-48c8-a3db-c0711eb499c6)

### Environment (with versions)?

Grafana: 10.2.0

OS:Ubuntu 20.04

Browser:Chrome 118.0.5993.71

### Grafana platform?

A downloaded binary

**Comment by tonypowa** [comment]
This issue is a test copy of an issue in another repo.  Original issue: https://github.com/grafana/grafana/issues/#77414

**Comment by moxious** [comment]
@support-agent Do we have similiar issues already?

**Comment by moxious** [comment]
**Triage summary**: TimeSeries panel displays incorrect data value after adjusting the time range, showing 160 instead of the expected 60, with no indication that the issue existed in previous versions. Steps to reproduce include enlarging the time interval for a certain value.

**Recommended labels**:

area/dashboard
type/bug
type/ux

**Comment by moxious** [comment]
Hi @tonypowa, it seems like you've encountered a UI issue with TimeSeries data visualization. This looks related to the Grafana frontend. I suggest transferring this issue to the **Frontend Platform project** so the appropriate team can investigate the display anomaly after adjusting the time range.

**Comment by moxious** [comment]
**Elaboration**:


Hi @tonypowa, 

Thank you for submitting the issue regarding the TimeSeries data display in Grafana. To help us understand the issue better and to provide a potential fix, we'll need some additional details:

1. Could you please clarify if you've observed this behavior with any specific datasource or if it happens across multiple datasources?
2. Are there any errors in the browser's console when the wrong data is displayed? If so, could you please share a screenshot or log output?
3. Does this issue occur consistently for the same time interval, or does it appear randomly?
4. Can you provide steps to reproduce the issue in a more detailed format or perhaps share the query you are using?
5. Is there any pattern to when the issue surfaces, such as after refreshing the dashboard, creating a new panel, or making changes to panel settings?

Further context on any configurations, panel settings, or data transformations applied might help us isolate the issue. Also, confirming the accuracy of the data returned from the datasource could help rule out a data retrieval problem.

Looking forward to your response so we can help you resolve this issue.

Best,
[Your Name]
