### ISSUE TITLE
Grafana does not listen to ipv6 requests (?)

### ISSUE THREAD

**Issue by usmangt** [moxious/triage#172]
**Why is this needed**:

I'm surprised not to find any configuration options for ipv6 listening, in grafana configuration file. Is it possible to listen to ::0 ?
I could use HAProxy to 'convert' ipv6 downstream to ipv4, but it would be way easier to have the ipv6 support in Grafana.

![image](https://github.com/grafana/grafana/assets/83098669/0c0b604e-a7b9-4730-bd3c-7e4a29460640)

**What would you like to be added**:

Is it possible to implement Grafana ipv6 support ?
It may already exist, sorry if I didn't find any docs about it.

**Who is this feature for?**

Anyone who want to embrace the future (even though ipv6 has already been a standard for at least twenty years)

Many thanks, and sorry if the feature exists and I didn't find it.

**Comment by usmangt** [comment]
This issue is a test copy of an issue in another repo.  Original issue: https://github.com/grafana/grafana/issues/78981

**Comment by moxious** [comment]
**Elaboration**:


Hi @usmangt, thank you for reaching out with your issue regarding IPv6 support in Grafana. To help you effectively, we would require a bit more information. Could you please provide the following details in your report?

- **Grafana Version**: What version of Grafana are you currently using?
- **Configuration Details**: How did you configure Grafana to listen to network requests? Please share the relevant portion of the configuration file (with sensitive information redacted).
- **Reproduction Steps**: Can you provide a step-by-step guide on how you encountered the issue? This can greatly help us in identifying the problem more concretely.
- **System Environment**: Can you share more about your running environment such as the operating system and its version?
- **Logs**: Are there any relevant Grafana log outputs or system logs when you try to set up IPv6? If so, can you include them here?

You provided a screenshot, but it unfortunately does not seem to load at the moment. Could you verify the link or upload the image again?

Getting this information will greatly assist our team in understanding the issue and exploring possible solutions for IPv6 support within Grafana.

We look forward to your response and are keen to resolve this as smoothly as possible for you and the community!

**Comment by moxious** [comment]
**Triage summary**: The author is requesting IPv6 support for Grafana, noting the absence of IPv6 configuration options and seeking either documentation or implementation of this feature.

**Recommended labels**:

area/backend
area/backend/networking
type/feature-request

**Comment by moxious** [comment]
Hello @usmangt, it sounds like this issue pertains to the core functionality of the Grafana server. Therefore, the Backend Platform project might be the best fit to address IPv6 support concerns. The team associated with that project would have the relevant expertise to potentially implement or guide you on this feature.

/backend-platform

**Comment by eleijonmarck** [comment]
@moxious The support-agent does clean out the "original" issue by it's id (number). Hence you get similiar issues by taking it from the issue number here #172 and it does not filter the original issue out #78981.

https://github.com/grafana/support-agent/blob/main/app/tools/github/search_issues_and_prs.py#L56
