### ISSUE TITLE
Dashboards: Removing expressions does not automatically refetch query

### ISSUE THREAD

**Issue by tonypowa** [moxious/triage#179]
### What happened?

After removing an expression from a panel the query did not reran until I either click refresh or hit apply

### What did you expect to happen?

For the queries on the panel to be re-ran after expressions are removed so that the chart gets updated properly without the expression

### Did this work before?

NA

### How do we reproduce it?

1. Open a panel from dashboard in edit mode and add an expression query.

2. After the chart get updated, click remove button of the expression query.

3. You will find the chart does not get updated after clicking the remove button.

### Environment (with versions)?

Grafana: 9.5.13 & 10.2.1 

OS: Windows

Browser: Edge

### Grafana platform?

None

### Datasource(s)?

Was able to repro across multiple

**Comment by moxious** [comment]
@support-agent Do we have similiar issues already?

**Comment by moxious** [comment]
**Triage summary**: When an expression is removed from a panel in edit mode, the query does not automatically refresh to update the chart, requiring manual refresh or hitting 'apply' to see changes.

**Recommended labels**:

area/dashboard
type/bug
area/expressions

**Comment by moxious** [comment]
Hello @tonypowa, thank you for bringing this to our attention. It seems like your issue pertains to the core functionality of Grafana dashboards. I'll tag this for the Dashboards Sharing squad to take a look, as they might be the best team to handle dashboard-related behaviors including expressions and queries. 

/team Dashboards Sharing squad

**Comment by moxious** [comment]
**Elaboration**:


Hi @tonypowa, thanks for raising this issue! Your detailed steps for reproduction are already quite helpful. To further investigate the issue, it would be beneficial to understand a few more aspects of the problem you're encountering. Could you please provide the following additional information? 

- **Screenshots or a screen recording**: Can you provide visuals showing the issue occurring? This can often provide context that words alone cannot. 
- **Console logs**: Are there any errors or warnings in the browser's developer console when the issue arises? If so, please include or attach them. 
- **Network requests**: When the issue occurs, are there any failed network requests? A screenshot of the network tab or a HAR export might be insightful. 
- **Any specific expressions**: Are there any specific expressions that are causing more trouble than others, or does it seem to occur with any expression you try to remove? 
- **Plugin versions**: Are you using any dashboard panel plugins? If so, what are the versions? 
- **Steps you’ve taken to attempt to resolve the issue**: Have you tried troubleshooting this issue on your own? For instance, does clearing the cache or using a different browser have any effect?

Once we have this information, we can better understand the problem and work towards a resolution. Thank you for your collaboration!
