### ISSUE TITLE
RBAC: Alert provisioning not enabled for Editors

### ISSUE THREAD

**Issue by tonypowa** [moxious/triage#180]
### What happened?

Trying to create or edit an alert rule via the new alert provisioning API gives this error:

```

Error: status: 403, body: {"accessErrorId":"ACE5486629262","message":"You'll need additional permissions to perform this action. Permissions needed: alert.provisioning:write","title":"Access denied"}

```

https://grafana.com/docs/grafana/latest/administration/roles-and-permissions/access-control/rbac-fixed-basic-role-definitions/#basic-role-assignments shows that editors are allowed to create alert rules (`fixed:alerting:writer`), however the permission `fixed:alerting.provisioning:writer` is missing.

### What did you expect to happen?

Alert rule created in Grafana via provisioning API.

### Did this work before?

The alert provisioning API is a relatively new feature and this permission was obviously missed.

### How do we reproduce it?

1. Create a user with role Editor

2. Call the alert provisioning API

### Environment (with versions)?

Grafana: 10.2.2

OS: Kubernetes 1.24

Browser: n/a

### Grafana platform?

Kubernetes

**Comment by tonypowa** [comment]
This issue is a test copy of an issue in another repo.  Original issue: https://github.com/grafana/grafana/issues/#79126

**Comment by moxious** [comment]
@support-agent Do we have similiar issues already?

**Comment by moxious** [comment]
Hello @tonypowa, thanks for reporting this. Based on the description you provided, I believe the **Alerting project** would be the most appropriate place for this issue. The problem pertains to RBAC (Role-Based Access Control) and Alert provisioning, which falls under the alerting capabilities of Grafana.

I'll add the appropriate labels for visibility to the Alerting project team. However, if you believe this issue fits better under a different project from the provided list, please let me know.

/cc @alerting-team

**Comment by moxious** [comment]
**Triage summary**: The issue reports that Editors cannot create or edit alert rules via the new alert provisioning API due to a missing `fixed:alerting.provisioning:writer` permission, resulting in a 403 error. It indicates that while the RBAC permissions for `fixed:alerting:writer` are set for Editors, the provisioning permission appears to be overlooked.

**Recommended labels**:

area/alerting
area/auth/rbac
type/bug
team/grafana-aws-datasources

**Comment by moxious** [comment]
**Elaboration**:


Hello @tonypowa,

Thank you for bringing up this issue regarding RBAC permissions for Editors with Grafana's new alert provisioning API. The details you've provided are a good start, but we could use a bit more information to help clarify and address the problem more effectively.

To assist you better, could you please provide the following additional details?

1. Steps to Reproduce Issue:
 - Please provide the exact API request (excluding any sensitive information) you made in step 2 of reproducing the issue.
 - Were there any specific configurations on the Editor role outside the standard permissions that might affect this?

2. Logs and Configurations:
 - Any relevant server logs that could provide more insight into the access denial.
 - The relevant part of the Grafana configuration file, if it’s customized in relation to roles and permissions.

3. Additional Context:
 - Have you been able to successfully perform other actions that the `fixed:alerting:writer` role is supposed to permit?
 - Is this issue consistently reproducible or does it happen intermittently?

Providing this information will help us better understand the context and technical details of the issue and allow us to investigate further.

Looking forward to your response.

Best regards,
The Grafana community support team
