### ISSUE TITLE
Explore: scroll to top breaking top buttom area position

### ISSUE THREAD

**Issue by tonypowa** [moxious/triage#184]
### What happened?

When toggle top search bar, and click log area "Scroll to top" buttom, query buttom area will move up a little position, and toggle top search bar will won't come back.

### What did you expect to happen?

Click "Scroll to top" not effect any component position, just scroll to top.

### Did this work before?

No

### How do we reproduce it?

1. In Explore page, click "Toggle top search bar" at right top corner.

2. Query logs, and click "Scroll to top" at right bottom corner.

3. Run query bottom bar will move up little position.

### Environment (with versions)?

Grafana: 10.2.2

OS: MacOS Ventura 13.6.1

Browser: Edge, Firefox

### Grafana platform?

Docker

### Datasource(s)?

Loki 2.9.2

**Comment by tonypowa** [comment]
This issue is a test copy of an issue in another repo.  Original issue: https://github.com/grafana/grafana/issues/#79196

**Comment by moxious** [comment]
@support-agent Do we have similiar issues already?

**Comment by moxious** [comment]
**Triage summary**: In the Explore section of Grafana, toggling the top search bar and then clicking the 'Scroll to top' button causes the query button area to move up, and the search bar does not reappear. The issue occurs using Edge and Firefox browsers on MacOS Ventura 13.6.1, with Grafana 10.2.2 running in Docker and Loki 2.9.2 as the datasource.

**Recommended labels**:

area/explore
area/frontend
type/bug

**Comment by moxious** [comment]
Hello @tonypowa, thank you for the bug report! It seems like you're experiencing an issue with the Explore feature on the frontend. I'm transferring this issue to the **Explore project** team as it's more closely related to their scope of work. They should be able to look into the unexpected UI behavior when using the 'Scroll to top' button within Explore.

**Comment by tonypowa** [comment]
useful elaboration points because i had trouble understanding the issue without a graphic example
