### ISSUE TITLE
Table visualization: sort order of column

### ISSUE THREAD

**Issue by tonypowa** [moxious/triage#185]
### What happened?

Click a column title to change the sort order from default to ascending to descending

### What did you expect to happen?

Click a column title to change the sort order from default to descending to ascending

![image](https://github.com/grafana/grafana/assets/19547279/aea760c0-8dce-4b16-ba41-5b561a453503)

### Did this work before?

Not work in version 10.0.3.

### How do we reproduce it?

1. create table

2. click on the column title

### Environment (with versions)?

Grafana: v10.0.3

OS: centos7

Browser: chrome 

### Grafana platform?

A downloaded binary

**Comment by tonypowa** [comment]
This issue is a test copy of an issue in another repo.  Original issue: https://github.com/grafana/grafana/issues/#79202

**Comment by moxious** [comment]
**Triage summary**: The issue reports an expected change in the sort order mechanism for table columns, preferring the sequence to be default-descending-ascending instead of the current default-ascending-descending.

**Recommended labels**:

area/panel/table
type/feature-request

**Comment by tonypowa** [comment]
the issue was easy to repro but not thanks to the steps the user gave
so elab points are relevant, specially the one asking for the exact steps, and on which version it used to work,

**Comment by tonypowa** [comment]
not sure why the bot thought that the dataviz squads maintains the table panel 
the actual maintainers are the bi squad
