### ISSUE TITLE
document the schema of `dashboard` in the `POST /dashboards/db` endpoint

### ISSUE THREAD

**Issue by tonypowa** [moxious/triage#189]
**Why is this needed**:

Not having a schema for an API endpoint makes it hard to know how to use it.

**What would you like to be added**:

A schema. Currently it's only defined as arbitrary JSON in the [swagger2](https://editor.swagger.io/?url=https://raw.githubusercontent.com/grafana/grafana/7181811f96f54bc6a88b84f28e0a2e86040b5201/public/api-merged.json) and [openapi](https://editor.swagger.io/?url=https://raw.githubusercontent.com/grafana/grafana/7181811f96f54bc6a88b84f28e0a2e86040b5201/public/openapi3.json) docs.

```json

 "SaveDashboardCommand": {

 "properties": {

 "UpdatedAt": {

 "format": "date-time",

 "type": "string"

 },

 "dashboard": {

 "$ref": "#/components/schemas/Json"

 },

```

https://github.com/grafana/dashboard-spec states:

> A SCHEMA IS NOW BEING BUILT DIRECTLY INTO GRAFANA ITSELF.

But I can't find one.

**Who is this feature for?**

Anyone who uses the `/dashboards/db` endpoint, and authors of libraries which work with the dashboard schema e.g. https://github.com/K-Phoen/grabana.

**Comment by tonypowa** [comment]
This issue is a test copy of an issue in another repo.  Original issue: https://github.com/grafana/grafana/issues/#79230

**Comment by moxious** [comment]
@support-agent Do we have similiar issues already?

**Comment by moxious** [comment]
Hello @tonypowa, thank you for bringing this to attention. The issue you've described seems most relevant to the **Backend platform project** as it pertains to the schema and API documentation which typically falls under backend responsibilities. I'll tag the issue accordingly and make sure the right team has visibility for potential inclusion of a schema in the API documentation.

```
/project Backend platform project
```

**Comment by moxious** [comment]
**Triage summary**: The issue requests documentation for the schema of the `dashboard` property in the `POST /dashboards/db` API endpoint, as it is currently only defined as arbitrary JSON and there is a need for a clear schema to be built directly into Grafana for better usage and integration.

**Recommended labels**:

area/backend/api
type/docs
area/dashboard

**Comment by moxious** [comment]
**Elaboration**:


Hello @tonypowa,

Thank you for bringing this to our attention. To better understand your request and to help our engineering team address it effectively, we'd appreciate it if you could provide further details:

1. Could you clarify if you are looking for a complete JSON schema definition that validates the structure of the dashboard JSON, including all possible fields and their data types?

2. Are there any specific fields or components in the `dashboard` JSON you've worked with or encountered issues with for which a clarified schema would be particularly helpful?

3. Have you tried using the endpoint with your own JSON dashboard definitions? If so, and if you've encountered errors or unexpected behavior, could you share an example of the JSON you used and the responses you received?

4. In reference to the ongoing effort to build a schema directly into Grafana, do you have any insights or recommendations on what this schema should include or prioritize based on your experience?

If you have any screenshots, error logs, or code snippets that could help illustrate your use case or the issues you've faced, those would be extremely useful too. 

Your feedback will help us make sure we document the schema in a way that best supports developers like yourself and the wider community.

Thank you for contributing to the project!
