### ISSUE TITLE
Edit Panel Configs in Multiple Components

### ISSUE THREAD

**Issue by tonypowa** [moxious/triage#192]
**Why is this needed**:

Today I have dashboards like this:

<img width="318" alt="image" src="https://github.com/grafana/grafana/assets/101121174/f09ce68f-1520-4a70-b8c1-1219093355e6">

So for me it's interesting to have an option to edit multiple components, in this case I use Stat and want to change all the colors in Threholds, but takes too much time to edit one by one.

**What would you like to be added**:

An option to edit only design(panel configs not query) in multiple components

**Who is this feature for?**

All users

**Comment by tonypowa** [comment]
This issue is a test copy of an issue in another repo.  Original issue: https://github.com/grafana/grafana/issues/#79269

**Comment by moxious** [comment]
@support-agent Do we have similiar issues already?

**Comment by moxious** [comment]
**Triage summary**: A feature request for editing panel configurations such as Thresholds colors in bulk across multiple Stat panels in a dashboard to save time as opposed to editing each one individually.

**Recommended labels**:

area/dashboard
type/feature-request

**Comment by moxious** [comment]
Hi @tonypowa, thank you for the feature request. It seems like your suggestion would directly impact how users interact with dashboards within the Grafana user interface. Therefore, I would recommend that this issue should be associated with the **Dashboards Sharing squad** project. This team specializes in enhancing the dashboard experience, including panel configurations and workflows for manipulating multiple panels at once.

/cc @dashboards-sharing-squad-team

**Comment by moxious** [comment]
**Elaboration**:


Thank you for reaching out with your feature request! Your suggestion regarding the configuration of multiple dashboard components at once to more efficiently manage design elements such as color thresholds seems interesting and useful. To help us better understand your needs and evaluate the feasibility of this feature, could you please provide some additional information? Here are a few questions that could clarify your request: 

1. Could you confirm the version of Grafana you are currently using?
2. Are there any specific scenarios or use cases where you've felt the need for this feature which you can share in more detail?
3. Would you want this feature to be available for all visualization types or specifically for the Stat panel?
4. How do you currently manage the threshold settings, and what challenges do you face when doing this for multiple components?
5. Could you please elaborate on how you envision the user interface for managing multiple components? For instance, how would a user select which components to edit, and how would changes be applied?

Having this additional context will help us consider the practical aspects of implementing your request. Thanks for suggesting enhancements to improve the Grafana user experience!
