### ISSUE TITLE
Dashboards: influxdbBackendMigration FF enabled - Breaks Template Variables with special characters

### ISSUE THREAD

**Issue by tonypowa** [moxious/triage#197]
### What happened?

Recently updated from v10.0.2 to v10.2.2. In doing so we discovered that public dashboards were broken. The fix was outlined to be enabling the FF 'influxdbBackendMigration' as per: https://github.com/grafana/grafana/issues/77648

Enabling the FF caused queries with template variables to no longer escape special characters, specifically ')'.

$device_name = /Test|Test (1)/

The Query attempting to be executed:

`SELECT (mean("field") FROM "measurement" WHERE ("device" =~ /^$device_name$/)`

In Query inspector, the executedQueryString is:

`SELECT mean(\"field\") FROM \"measurement\" WHERE \"device\" =~ /^Test|Test (1)$/`

The above query returned no data.

### What did you expect to happen?

The executedQueryString would be expected to look like: 

`SELECT mean(\"field\") FROM \"measurement\" WHERE \"device\" =~ /^(Test|Test \\(1\\))$/)`

### Did this work before?

The query works in the current version (v10.2.2) without 'influxdbBackendMigration' FF enabled.

The executedQueryString with FF disabled is:

`SELECT mean(\"field\") FROM \"measurement\" WHERE \"device\" =~ /^(Test|Test \\(1\\))$/)`

### How do we reproduce it?

1. 'influxdbBackendMigration' FF disabled

2. Create a dashboard with a template variable that contains 2 or more values, at least one of them with a special character such as '('

3. Create a panel that queries the template variable and confirm this is working

4. enable FF 'influxdbBackendMigration'

5. Query should stop returning data for the value with a special character and executedQueryString will be formatted different to the original query

### Environment (with versions)?

Grafana: 10.2.2

Browser: Chrome

### Grafana platform?

None

### Datasource(s)?

influxDB v1.8

**Comment by tonypowa** [comment]
This issue is a test copy of an issue in another repo.  Original issue: https://github.com/grafana/grafana/issues/#79368

**Comment by moxious** [comment]
@support-agent Do we have similiar issues already?

**Comment by moxious** [comment]
**Triage summary**: After enabling the 'influxdbBackendMigration' feature flag, template variables with special characters such as parentheses are no longer escaped correctly, which breaks queries and returns no data in Grafana v10.2.2 using InfluxDB v1.8.

**Recommended labels**:

area/datasource
type/regression
datasource/InfluxDB

**Comment by moxious** [comment]
Hi @tonypowa, thanks for reporting this issue. It seems that you're facing a problem related to query parsing for template variables in dashboards with the influxdbBackendMigration feature flag. I believe this issue is best suited for the **Backend platform project**, as it appears to involve query parsing and backend migration logic with InfluxDB as the datasource.

I'm tagging this for the Backend team's attention: @grafana/backend-platform

In the meantime, reverting the 'influxdbBackendMigration' feature flag seems to be your temporary workaround.

**Comment by moxious** [comment]
**Elaboration**:


Hi @tonypowa, thank you for the detailed report! :wave: It seems like you've identified a specific regression related to the influxdbBackendMigration feature flag and special characters in template variables. To help us delve deeper into this issue, could you please answer a few additional questions and provide some further details? :mag_right:

1. **Screenshots**: Could you provide screenshots of the dashboard panel configuration where the template variable is defined, and where it's being used in the query prior to enabling the 'influxdbBackendMigration' flag? A screenshot after enabling the flag displaying the incorrect executedQueryString might also be helpful.

2. **Browser Console Logs**: Are there any errors in the browser console when the query fails to return data? Errors logged here could give us insight into what might be happening behind the scenes.

3. **Additional Configuration**: Is there any other Grafana configuration or proxy setup that might affect the query's behavior?

4. **InfluxDB Logs**: It would help to see if InfluxDB is logging any errors when the query is executed. Could you share the relevant logs from the InfluxDB side?

5. **Escaping Mechanism**: If possible, please clarify how the special characters were being escaped in the version prior to the feature flag change. Understanding the previous mechanism might help identify what the migration might have overlooked.

6. **Reproduction**: Finally, just to cover all bases, could you provide a step-by-step guide on how to replicate the template variable and query set up on a clean Grafana install, possibly with a minimal dataset to test against? This might help us reproduce the issue independently and identify the regression.

Thank you for your cooperation. Your input will be crucial for our team to pinpoint and address the issue more effectively. :hammer_and_wrench:

**Comment by tonypowa** [comment]
good tags
wrong project (should be metrics squad)
