### ISSUE TITLE
Color scheme (by value) thresholds per column not per table

### ISSUE THREAD

**Issue by tonypowa** [moxious/triage#198]
Hello

I will provide a basic example for a better understanding of this feature request.

I run two queries returning two sets of results with a identical common field. I Outer join by that field to obtain this table output:

(I am not sure if relevant or not how the table is generated, I suppose it can work with single queries as well)

![image](https://github.com/grafana/grafana/assets/22320901/b9a1fc3c-e2ac-4e31-bd62-c5087878e988)

the mix and max per column are very different

0.06 to 1.4 on the first column

1.93 to 840 on the second column

I then apply a cell display mode override "Gradient Gauge" and a color scheme "green-yellow-red" by value and I obtain the following results:

![image](https://github.com/grafana/grafana/assets/22320901/58b1d8c8-875c-4005-8529-eb4553dcd8f4)

![image](https://github.com/grafana/grafana/assets/22320901/70865ec0-2e65-4982-b929-7b6bfc57c5e9)

Judging by how the colors are displayed it looks like the color scheme and the gradient gauge will take into consideration the min and the max for all the values in the table. from 0.06 to 840

While this is useful in certain situations, we should also have the possibility to chose and have these thresholds per column instead of per table as it is configured by default.

Currently I am using a workaround which implies the definition of manual thresholds values/colors and then setting static max/min limits for each column. This is not ideal when working with dashboards based on variables as the thresholds values will not apply to other similar tables in different context.

Thank you for looking at this feature request.

This was originally posted in 

https://github.com/grafana/grafana/discussions/58824

**Comment by tonypowa** [comment]
This issue is a test copy of an issue in another repo.  Original issue: https://github.com/grafana/grafana/issues/#79377

**Comment by moxious** [comment]
@support-agent Do we have similiar issues already?

**Comment by moxious** [comment]
**Triage summary**: The feature request is for the ability to set color scheme thresholds per column rather than per table in Grafana datagrid panels, as currently the gradient gauge and color schemes consider the min and max across the entire table. The author is currently using a workaround by defining manual thresholds values and setting static max/min limits for each column, which is not ideal.

**Recommended labels**:

area/panel/datagrid
area/panel/common
type/feature-request

**Comment by moxious** [comment]
Hello @tonypowa, 

Thank you for providing a detailed explanation of your feature request regarding color scheme thresholds for individual columns. It appears that your request fits best with the **DataViz project**, where enhancements to visualization features including table views and gradient color schemes are typically evaluated and implemented.

A member of the DataViz team should be able to further assess your request and consider it for possible inclusion in the project's roadmap.

All the best,
Github Assistant

**Comment by moxious** [comment]
**Elaboration**:


Thank you for providing a detailed feature request! To ensure that we fully understand your requirement and to assess the feasibility of this feature, could you please provide a bit more information? Here are some clarifying questions that would help us move forward:

- Could you specify which version of Grafana you are using?
- Is the 'Gradient Gauge' and color scheme override you're referring to part of the core Grafana functionality, or is it a community plugin? If it's a plugin, please mention its name and version.
- When you mention manual thresholds, could you elaborate on how you're currently setting these? Are these set through the Grafana UI, or are they part of a programmatic definition (e.g., in a JSON model or a script)?
- Could you provide a specific example or a mockup showing how you'd expect the column-specific thresholds to be configured and visualized in the Grafana interface?
- Have you noticed any performance implications with your current workaround when dealing with large datasets?
- Lastly, could you share the JSON model of the dashboard panel where this feature would be integrated (if applicable and without any sensitive information)?

This additional information will help us gauge the scope of the request and understand the impact on existing functionality. Thank you for your contribution to the community!
