### ISSUE TITLE
Annotations: Set prev/new states through API

### ISSUE THREAD

**Issue by tonypowa** [moxious/triage#200]
**Why is this needed**:

To allow using native annotations for other alerting systems.

If there is any solution to set annotation state throught API I wll be appreciated for the help.

**What would you like to be added**:

Add prevState and newState fields in the request payload for:

`POST, PUT, PATCH /annotations` and allow to filter by these fields in `GET /annotations`

**Who is this feature for?**

Developers

**Comment by tonypowa** [comment]
This issue is a test copy of an issue in another repo.  Original issue: https://github.com/grafana/grafana/issues/#79399

**Comment by moxious** [comment]
@support-agent Do we have similiar issues already?

**Comment by moxious** [comment]
**Triage summary**: The user requests enhancement of the annotations feature by allowing prevState and newState fields in the API request payload for creating and updating annotations, and additionally being able to filter by these fields when retrieving annotations.

**Recommended labels**:

area/api
type/feature-request
area/annotations

**Comment by moxious** [comment]
Hi @tonypowa, it seems like you're referring to the creation and update of annotations through the API, which could be related to the Backend Platform project, as it appears to involve backend API enhancements for annotation features. However, if this pertains specifically to the alerting functionality and integration with other systems, it could possibly fit within the Alerting project as well. Could you please provide more context on how these annotations are used within the Grafana ecosystem in your case? That would help us determine the most suitable project for this feature request.

**Comment by moxious** [comment]
**Elaboration**:


Hello @tonypowa, 

Thank you for submitting your feature request! I see that you would like to enhance the API by adding `prevState` and `newState` fields for annotation states. To better understand your request and ensure it's actionable, could you please provide a bit more information?

- Could you elaborate on the specific use case or workflow where these additional fields would be beneficial? 

- Are you currently using a workaround that is insufficient, and if so, how does it fall short?

- Can you provide an example of the payload you would like to send, and the expected response from the API?

- Lastly, adding these fields might require changes in the API's logic; do you foresee any potential backward compatibility issues?

Any additional context or examples you provide will help us evaluate the feature request more effectively. Thank you for participating in the community!
