### ISSUE TITLE
allow to disable queries based on (multi)variables

### ISSUE THREAD

**Issue by tonypowa** [moxious/triage#206]
Hey

It seems that Grafana has unfortunately only limited support for scenarios of repeated panels (like having a dashboard where each panel plots the network IO for a single host of a larger cluster).<br>

One feature I've already requested was to get common scaling for such repeated graphs (#79548).

Another one would be to allow disabling queries based on a (multi)variable.

**Why is this needed**:

When on has single panels, disabling it's contained graphs can already be done more or less by hiding them via clicks on their entry in the legend.<br>

This affects however only that one panel, even if it's repeated over some variable.

Now consider for example that one has a dashboard which gives an overview over the loads of all hosts like in:

![Screenshot from 2023-12-24 05-06-58](https://github.com/grafana/grafana/assets/919933/145ff40f-517f-4020-bc36-f10f3b0ec92b)

If here one wants to see only a selection of the three load types (1m, 5m, 15m) **for all** the panels, clicking through each of them is not a viable option.

Instead one wants to control this via a variable, which then can also be used in URLs as a nice benefit.

While searching for this I found quite a few entries on stackoverflow, or in the grafana community forums, where people wanted to do the same, so I'm really surprised it's not possible, especially as this seems like base functionality to me.<br>

Anyway, people came up with various workaround (rather hacks) to get this, e.g.

- https://community.grafana.com/t/change-grafana-query-dynamically-based-on-user-inputs/26416/4

 Putting the whole query behind one of the keys of the variable, and leaving the other key empty.<br>

 I guess this has the advantage of not causing a potentially expensive query to run, when it's not needed anyway, but the big disadvantage that it's just ugly and doesn't integrate at all with the editor.

- https://stackoverflow.com/questions/66917146/show-or-hide-query-result-depending-on-variable-value-in-grafana

 Dividing (respectively multiplying) by `0` or `1` (respectively vice versa), depending, which are stored as value for the key of a variable.<br>

 Less ugly, but the big disadvantage is, that the rest of the query is probably still executed for nothing.

For the latter there was even a nice [trick](https://stackoverflow.com/a/70217080/6646161) using the modulus operator, to allow a single variable to filter multiple queries .

All of them are just workaround and especially, AFAICS, none of them can be made working with multi-value variables.<br>

So in case of my load example above, I'd need three variables, where each acts as a on/off switch for one of the three load types. The modulus-operator tricks doesn't really help here, because it would allow my to select only exactly one of the three for plotting or all three. But not - at least not properly - any combination of two.

**What would you like to be added**:

Some way that allows one to disable a query/field via a (multi-)variabe.

That is, if I have a multi-value variable for load with keys `1m`, `5m`, `15m`, and `All`… I'd like to be able to select any combination of the first 3 as well as all, and get the respective of three different queries (e.g. PromQL on `node_load1`, etc.) in one panel be enabled/disabled.

**Who is this feature for?**

Everyone who wants to control the plotted graphs in multiple repeated panels all at once, but also anyone who wants to control via URL which graphs are actually plotted.

Thanks,

Chris.

**Comment by tonypowa** [comment]
This issue is a test copy of an issue in another repo.  Original issue: https://github.com/grafana/grafana/issues/#79848

**Comment by moxious** [comment]
**Summary**: User tonypowa requests the ability to disable Grafana queries based on multi-value variables. The feature would help users control the visibility of graphs across repeated panels from a single variable and would also work with URLs. People have been using unsatisfactory workarounds, but a more integrated and cleaner solution is sought.

**Comment by moxious** [comment]
Hi Chris, 

Thanks for sharing this detailed request about panel query control with variables! It sounds like a feature enhancement for the Grafana front-end experience. Given the focus on panel functionality and dashboard manipulation using variables, I'd suggest this issue belongs to the Frontend Platform project. The Grafana team responsible for dashboard UI and UX can evaluate the feasibility of such a feature based on the use cases you've described.

Best regards, 
Your Helpful GitHub Assistant

**Comment by moxious** [comment]
**Elaboration**:


Hi Chris (@tonypowa),

Thank you for detailing your use case regarding Grafana's current functionality and your need for better control over the queries, especially in dashboards that utilize repeated panels.

To make sure the team fully understands your request and to assess the potential for implementation, could you please provide a few additional pieces of information?

1. **Version of Grafana**: Could you confirm the specific version of Grafana you are using where this feature is missing?
2. **Detailed Steps for Reproduction**: While you've described the scenario well, it would be helpful to have a step-by-step guide for reproducing the issue. This would include any dashboards or queries you’ve set up that are relevant.
3. **Configuration Snippets or Screenshots**: Besides the use-case screenshot you provided, could you share any configuration snippets (anonymized as necessary) or additional screenshots of your current setup that highlight the problem?
4. **Expected vs Actual Behavior**: In your ideal implementation, how would you expect the interface or feature to behave? Could you please describe it?

These details will help in understanding the precise nature of the feature request and evaluating its feasibility. We appreciate your effort in contributing to the Grafana community and look forward to your response!

Best regards,
The Grafana Community Team
