### ISSUE TITLE
Certain Visualizations Disappear on Low-Performant Devices

### ISSUE THREAD

**Issue by tonypowa** [moxious/triage#208]
### What happened?

It seems that certain visualizations on a dashboard disappear after a little while when Grafana is displaying on a low-performant device. In my case, I have an old Raspberry Pi 3 B+ running a 1080p monitor to show this dashboard 24/7. Initially, when the dashboard loads, everything displays and refreshes properly. But after a few hours, the content of certain visualizations disappear in the panel. Currently, I have only noticed this with graph-based visualizations, such as time graph and bar chart. Other visualizations like the table or stats panel continue to function normally.

![20231214_212121](https://github.com/grafana/grafana/assets/77515137/e1f2c224-05c8-48d5-87fa-e4c7f371fece)

### What did you expect to happen?

Visualizations to function normally over time.

### Did this work before?

This works initially, when the dashboard loads up for the first time. But after a few hours, certain visualizations just disappear and no edits are made to the dashboard during this time, nor is there loss of network connectivity.

### How do we reproduce it?

1. Create a dashboard with time graphs and/or bar charts

2. Setup an older Raspberry Pi and display the dashboard in kiosk mode on Chromium browser

3. Wait a few hours, displaying it the entire time, and it should replicate the disappearing issue

### Environment (with versions)?

Grafana: 10.2.2

OS: Raspberry Pi OS 64-bit (latest version)

Browser: Chromium browser (built-in)

### Grafana platform?

None

### Datasource(s)?

Prometheus

**Comment by tonypowa** [comment]
This issue is a test copy of an issue in another repo.  Original issue: https://github.com/grafana/grafana/issues/#79578

**Comment by moxious** [comment]
**Summary**: On low-performant devices like Raspberry Pi 3 B+, certain graph-based visualizations in Grafana dashboards such as time graph and bar charts disappear after several hours of display, while other types like tables remain properly visible.

**Comment by moxious** [comment]
Hi @tonypowa, this issue appears to be related to rendering or performance concerns with certain visualizations within Grafana. It may be best associated with the **Frontend Platform project** due to its focus on visual components and the end-user's experience in a browser. The Frontend team would possess the insight required to investigate potential memory leaks or performance issues, especially on less capable hardware like the Raspberry Pi 3 B+.

```markdown
Thanks for reporting this issue. It sounds like there might be a performance-related problem with rendering dashboards on less powerful devices. Have you encountered this issue with other browsers or just Chromium? Additionally, does reducing panel complexity or using the lightweight dashboard theme influence the problem's occurrence?

You may want to follow these steps meanwhile:

1. Check for any JavaScript errors in the browser's development console when the issue occurs.
2. Confirm that the Raspberry Pi's hardware resources are not being overtaxed during the display of the dashboard.
3. Upgrade to the latest version if possible and retest, as there might have been performance improvements or bug fixes.

This information could provide valuable clues to resolve the performance issues you're experiencing.
```

Hopefully, the Frontend team can provide further guidance or a solution to this problem. Thank you for bringing it to the community's attention.

**Comment by moxious** [comment]
**Elaboration**:


Thank you for submitting your issue and for the detailed description of the problem you're encountering with the Grafana dashboard on a low-performance device. To help us further investigate the issue, it would be beneficial to have a bit more information. Could you please provide the following additional details?

1. **Error Logs**: Are there any error messages displayed on the browser's console or within Grafana's server logs when the visualizations disappear?

2. **Resource Usage**: Have you monitored the system resources (CPU, memory) of your Raspberry Pi during the dashboard's operation? If the resources are maxed out, this could contribute to the issue. Details on the resource usage could help us understand if there's a performance bottleneck.

3. **Browser Version**: Could you confirm the specific version of the Chromium browser you are using?

4. **Network Requests**: When the visualizations fail, could you inspect if there are any failed network requests via the browser's Developer Tools (typically can be opened with `F12` key) in the Network tab?

5. **Panel JSON**: It might be helpful if you could share the JSON configuration of a visualization panel that consistently fails.

6. **Screen Capture or Video**: If possible, a short video or screen capture showing the problem in action could offer more context.

7. **Steps Tried**: Have you tried some common debugging steps like clearing the browser cache, restarting Grafana, or updating the Raspberry Pi’s operating system and browser?

Once you can provide these additional pieces of information, we should have a clearer picture of what might be causing this issue. Thank you again for your cooperation!
