### ISSUE TITLE
Data Sources: Provisioning config updated, but changes not reflected in Grafana

### ISSUE THREAD

**Issue by tonypowa** [moxious/triage#212]
### What happened?

In Grafana 10.2.x, I have made a change to a datasource, namely a http header value, but also the `editable` flag, but these changes have not been reflected back in Grafana, they are using the old configuration. When I look at the mysql database for the datasource after the provisioning file has been updated and Grafana restarted, the data in the database is completely unchanged. I used the editable flag as a good canary for this because it's unencrypted and therefore would be easy to see the read_only column in the data_source table switch from 1 to 0, but it has not.

### What did you expect to happen?

I expected the changes to the provisioning file to be picked up during a restart of Grafana (or even after 10 minutes of Grafana running), and the changes be visible (or at least the effects of the changes visible WRT changing header values) in the UI.

### Did this work before?

10.0.x

### How do we reproduce it?

1. Create a datasource provisioning file which looks similar to this:

```

 {

 "access": "proxy",

 "editable": false,

 "jsonData": {

 "httpHeaderName1": "X-Scope-OrgID",

 "incrementalQuerying": true,

 "prometheusType": "Cortex",

 "prometheusVersion": "1.14.0",

 "timeInterval": "30s"

 },

 "name": "Foobar",

 "orgId": 1,

 "secureJsonData": {

 "httpHeaderValue1": "foobar",

 },

 "type": "prometheus",

 "url": "http://prometheus:9090/",

 "version": 1

 },

```

2. Start grafana

3. Update the provisioning file like so:

```

 {

 "access": "proxy",

 "editable": true,

 "jsonData": {

 "httpHeaderName1": "X-Scope-OrgID",

 "incrementalQuerying": true,

 "prometheusType": "Cortex",

 "prometheusVersion": "1.14.0",

 "timeInterval": "30s"

 },

 "name": "Foobar",

 "orgId": 1,

 "secureJsonData": {

 "httpHeaderValue1": "foobar",

 },

 "type": "prometheus",

 "url": "http://prometheus:9090/",

 "version": 1

 },

```

4. Restart Grafana

5. Check to see that there are no changes

### Is the bug inside a dashboard panel?

n/a

### Environment (with versions)?

Grafana: 10.2.2 and 10.2.3

OS: Linux / Kubernetes

Browser: Edge

### Grafana platform?

Kubernetes

### Datasource(s)?

Prometheus

**Comment by tonypowa** [comment]
This issue is a test copy of an issue in another repo.  Original issue: https://github.com/grafana/grafana/issues/#79694

**Comment by moxious** [comment]
**Elaboration**:


### Thank you for submitting the issue! :tada:

It looks like you've experienced an issue with data source provisioning in Grafana not taking effect after making some configuration changes. To help the maintainers investigate this issue thoroughly, I have a few questions that would help clarify the situation:

1. Could you please confirm if there are any errors in the Grafana logs after restarting the service? This would help establish whether Grafana is encountering issues when processing the updated provisioning files.

2. Have you tested this issue with the simplest possible provisioning configuration to determine whether the issue persists even then?

3. Are you able to reproduce this issue consistently on the affected versions (10.2.2 and 10.2.3) and did the issue only start after upgrading to these versions?

4. Could you provide details on the permissions of the provisioning file? It would be helpful to know if Grafana has the necessary permissions to read the updated provisioning file.

5. In the reproduction steps, you've mentioned checking to see that there are no changes. Could you please provide more details on where exactly you're checking for these changes? In the Grafana UI, API responses, or elsewhere?

6. Lastly, if you have any screenshots, logs, or any additional information that demonstrates the lack of changes in the data source configuration after the update is applied and Grafana is restarted, that would be very helpful for troubleshooting.

Providing the above details will better equip the maintainers to understand and address your issue. Looking forward to your response!

**Comment by moxious** [comment]
Hi @tonypowa, it seems like you are reporting an issue related to datasource provisioning which can be associated with the `Backend platform project`. The developers working on the backend are likely to have more context on the provisioning system and its interactions with the database.

Would you be able to provide any logs that show the provisioning system being triggered after you change the configuration? That might help diagnose the issue.

Also, it might be helpful to ensure that there are no permission issues with the updated files, especially if Grafana is running in Kubernetes. The Grafana pod needs to have the correct permissions to read the updated provisioning files.
