### ISSUE TITLE
Grafana OSS: Explorer For Traces with tempo errors with `NaN` if limit is set to auto

### ISSUE THREAD

**Issue by tonypowa** [moxious/triage#226]
### What happened?

![Screenshot 2023-12-28 at 15 51 25](https://github.com/grafana/grafana/assets/14996407/9e30362a-4f44-45c3-b2fd-7fee8027501d)

### What did you expect to happen?

Either Autolimit or paginate over traces

### Did this work before?

🤷 

### How do we reproduce it?

1. Go to explore

2. Choose Traces

3. Delete number in the `limit` field

4. run query

### Environment (with versions)?

Grafana: Grafana v10.2.1 (533a733e4eda44041e43358c5a51203e9b42c9ea)

OS: MacOS 14.2.1 (23C71)

Browser: Chrome

### Grafana platform?

Kubernetes

### Datasource(s)?

Tempo

**Comment by moxious** [comment]
Hello @tonypowa, thank you for reporting this issue. It sounds like you're experiencing trouble with Traces in Grafana. As this involves the `tempo` datasource and the tracing functionality in Grafana, I believe the Traces & Profiling project is the best fit for this issue. I'll label and forward the issue accordingly to ensure the right team is aware of this behavior with auto-limited traces.

**Comment by moxious** [comment]
**Summary**: Issue 226 in Grafana OSS is OPEN where the Explorer for Traces with Tempo datasource returns `NaN` when the limit is set to auto. The user expects auto-limit or pagination over traces but encounters an error upon executing the query with auto limit. Reproduction steps are provided and it occurs on Grafana v10.2.1 on MacOS with Chrome.

**Comment by moxious** [comment]
**Elaboration**:


Hi @tonypowa, thank you for reaching out to the Grafana OSS community with your issue report! Your screenshot and the steps you've provided give a good starting point, but to help us better understand and replicate the issue, we would require some additional information. Here's what would be really helpful for our investigation:

1. **Error Messages:** Please provide any error messages or console logs that appear when the issue occurs.
2. **Configuration:** Are there any specific settings in Grafana or Tempo that could be relevant to this issue? Sharing those configurations might help.
3. **Network Details:** If possible, capture and share the network requests and responses when the issue happens (browser Developer Tools > Network tab can be used for this purpose).
4. **Reproducibility:** Does the issue happen consistently when you follow the steps, or is it intermittent? If intermittent, any idea on how often or under what circumstances?
5. **Screenshot Accessibility:** The link to the screenshot provided seems to be broken or inaccessible. Can you please double-check the link or upload the image again for reference?

Having these additional details will greatly enhance our ability to replicate and troubleshoot the issue you're experiencing. We appreciate your collaboration to improve Grafana!

Looking forward to your response,
The Grafana OSS team
