### ISSUE TITLE
Grafana 10.2.2 > Alerting >Alert rule >(folder)>Noraml(No data {in alert grafana_state_reason:NoData}

### ISSUE THREAD

**Issue by tonypowa** [moxious/triage#228]
After Grafana upgrade from 8.3.10 to 10.2.2, after creating an alert rule and fired to alert we are getting below error which is in grafana_state_reason:NoData

![image](https://github.com/grafana/grafana/assets/100562921/8cb52f21-c5c0-40e7-8625-62f2a3cba11d)

**What did you expect to happen?**

don't get NoData in the grafana_state_reason tab in alerts

**Did this work before?**

Yes, in the 8.3.10 version, it is giving exact mentioned value 

**How do we reproduce it**:

1.install grafana latest 10.2.2

2. create an alert in the dashboard

3. set alerting contact point to email

**Is the bug inside a dashboard panel?**

I think yes

**Environment (with versions)?**

Grafana: latest (10.2.2)

OS: Ubuntu 22.04

Datasource(s)? : Prometheus -2.33.3

Browser: google

**Comment by tonypowa** [comment]
This issue is a test copy of an issue in another repo.  Original issue: https://github.com/grafana/grafana/issues/#79906

**Comment by moxious** [comment]
**Summary**: Issue in Grafana 10.2.2 where alert rules are incorrectly showing a 'NoData' state in 'grafana_state_reason' after an upgrade from version 8.3.10. The problem did not exist in the earlier version, and steps to reproduce include creating an alert rule and setting an email contact point in the latest Grafana version on Ubuntu 22.04 with Prometheus as the data source.

**Comment by moxious** [comment]
Hello @tonypowa, it seems like the issue you're experiencing is related to Alerting in Grafana. This potentially is an issue with the new Unified Alerting system introduced in recent versions of Grafana. I would suggest redirecting this issue to the **Alerting project** where the team responsible for alerting functionalities can take a closer look at this problem.

Meanwhile, you might want to check if there were any breaking changes regarding alerting from version 8.3.10 to 10.2.2 or any migration steps that might have been missed during the upgrade.
