### ISSUE TITLE
[BUG] When swithching the organisation, getting redirected to loacalhost3000 

### ISSUE THREAD

**Issue by tonypowa** [moxious/triage#233]
### What happened?

When switching to another organisation from the current organisation it replaces the domain with localhost:3000, for the first time and if trying to swithch to same organisation in other tab for the second tab it is working fine. This is happening for each organisation swithch for the first time and for second time for the same organisation it is working fine

### What did you expect to happen?

Switching organisation should not redirect to localhost

### Did this work before?

No

### How do we reproduce it?

1.Try deploying grafana through a reverse proxy.

2. Create multiple Organisation.

3. Try Switching the organisation 

### Is the bug inside a dashboard panel?

Yes

### Environment (with versions)?

Grafana: 10.1.5

OS: Linux

Browser: Chrome

### Grafana platform?

Docker

**Comment by tonypowa** [comment]
This issue is a test copy of an issue in another repo.  Original issue: https://github.com/grafana/grafana/issues/#80073

**Comment by moxious** [comment]
**Summary**: The issue #233, is an OPEN bug reported by tonypowa, where switching to a different organization in Grafana redirects the user to localhost:3000 on the first attempt but works correctly on subsequent attempts. This occurs when Grafana is deployed through a reverse proxy.

**Comment by moxious** [comment]
Hello @tonypowa, thank you for reporting this issue. It seems like it could be related to the **Identity and Access project**, as organization switching is typically associated with access control and identity management. However, switching the organization should not redirect you to localhost, so it could also be connected to how base URLs are handled, which might be part of the **Frontend Platform project**. To ensure the right team sees this, could you provide any additional context on your reverse proxy configuration? Meanwhile, I'm flagging this for the **Identity and Access project** team to take a first look.

**Comment by moxious** [comment]
**Elaboration**:


Hello @tonypowa, thank you for reporting this issue. I'd like to gather a bit more information to help us pinpoint the issue accurately. Here are some questions that would help us proceed with the troubleshooting process:

- Could you check whether there are any console errors in the browser's developer tools when the redirection to `localhost:3000` occurs? If so, could you please provide the output here?
- Would you be able to share your reverse proxy configuration, ensuring any sensitive information is removed? This would help us recreate your setup.
- Can you confirm if you have any Grafana configuration settings (grafana.ini or environment variables) that might be related to the base URL or domain settings? If so, please provide details.
- Could you also clarify if the issue occurs when you switch organizations by using the Grafana UI, or if it occurs when you're using direct links/URLs?
- Have you noticed any pattern or specific conditions under which this issue consistently appears?

Any additional information about your configuration or relevant logs from Grafana when the issue occurs could be greatly beneficial. If it's possible and relevant, a screen recording of the issue happening might also help visualize the behavior.

Looking forward to your response to assist you further!
