### ISSUE TITLE
Alerting: Notifications are sent to the wrong contact point with nested policies

### ISSUE THREAD

**Issue by tonypowa** [moxious/triage#237]
### What happened?

<img width="1930" alt="Screenshot 2024-01-09 at 6 35 51 PM" src="https://github.com/grafana/grafana/assets/6930365/f0eb8857-53bd-49bf-a64b-ad70dcd094a3">

<img width="788" alt="Screenshot 2024-01-10 at 12 41 44 AM" src="https://github.com/grafana/grafana/assets/6930365/1be5d4bd-561c-45b0-a018-6b81efd769c2">

### What did you expect to happen?

Even though an alert is recognized as "message =~ .:closed." and shows "1 instances" on the policy,

notification is being sent to "slack-alerts" (see the first screenshot) instead of "slack-warnings" which is the contact point of the parent's policy, not the children's.

### Did this work before?

No

### How do we reproduce it?

1. Configure a receiver R1 in the default notification policy

2. Create a child policy A that matches foo = bar label and do not define a receiver

3. Create a child policy X under A that matches x = y label and defines a receiver R2

4. Create an alert with labels foo = bar and x = y

5. Confirm in Preview Routing that policy X is used.

6. Cause the alert to trigger and send a notification

7. Confirm if the notification was sent to receiver R1 or R2

### Environment (with versions)?

Grafana: 

Grafana v10.3.0-64399 

OS:

Browser:

### Grafana platform?

I use Grafana Cloud

**Comment by tonypowa** [comment]
This issue is a test copy of an issue in another repo.  Original issue: https://github.com/grafana/grafana/issues/#80265

**Comment by moxious** [comment]
**Summary**: Issue 237 remains open, where notifications are being sent to the incorrect contact point in Grafana when dealing with nested alerting policies, contrary to the user's expectations based on policy configurations.

**Comment by moxious** [comment]
It seems like this issue is related to the alerting system and its routing logic. Based on the description provided, I believe this should be directed to the **Alerting project** team as it best fits the context of notification policies and contact points. @tonypowa, someone from the Alerting project should be able to assist you with this issue.
