### ISSUE TITLE
Grafana-Altering: Appearing error message ""Missing receiver" and "Missing group labels" after sending test notification

### ISSUE THREAD

**Issue by tonypowa** [moxious/triage#239]
### What happened?

We configured the SMTP connecttion in /etc/grafana/grafana.ini to enable sending emails by Grafana Altering, but the following error appeared:

![error-1](https://github.com/grafana/grafana/assets/40660586/026f5c00-8f50-4bc8-a045-1e9d5f2eea14)

We checked Grafana log file at /var/log/grafana/grafana.log and found this:

![error-2](https://github.com/grafana/grafana/assets/40660586/85a39eaf-e8db-48a2-97a6-bb1a6da4d2ea)

### What did you expect to happen?

A test notification email should be received by our email contact point.

### Did this work before?

No, it didn't.

### How do we reproduce it?

1.Edit the configuration file "/etc/grafana/grafana.ini" like this:

#################################### SMTP / Emailing ##########################

[smtp]

;enabled = false

enabled = true

;host = localhost:25

host = \<your host\>:\<your port\>

;user =

user = \<your email\>

\# If the password contains # or ; you have to wrap it with triple quotes. Ex """#password;"""

password = <your email's Authorization code>

;cert_file = 

;key_file = 

;skip_verify = false

;from_address = admin@grafana.localhost

from_address = \<your email\>

from_name = Grafana

\# EHLO identity in SMTP dialog (defaults to instance_name)

;ehlo_identity = dashboard.example.com

\# SMTP startTLS policy (defaults to 'OpportunisticStartTLS')

;startTLS_policy = NoStartTLS

2.Configure recipient address at Grafana->Altering->Contact points like this:

![error-3](https://github.com/grafana/grafana/assets/40660586/718cb14b-2708-4c43-bb53-773737502e11)

3.Send a test notification and the error appeared:

![error-1](https://github.com/grafana/grafana/assets/40660586/f6f362b3-72cb-40e8-ad7d-b2eed6f8f706)

### Environment (with versions)?

Grafana: v8.5.0

OS: Grafana deployed on Linux, Grafana WebUI displayed on Windows

Browser: Chrome

### Grafana platform?

A package manager (APT, YUM, BREW, etc.)

**Comment by tonypowa** [comment]
This issue is a test copy of an issue in another repo.  Original issue: https://github.com/grafana/grafana/issues/#80267

**Comment by moxious** [comment]
Hi @tonypowa, it seems like this issue is related to the alerting mechanism in Grafana. 
For proper visibility and support, I'm going to redirect this issue to the **Alerting project**. The team associated with that project can provide specific expertise regarding notification channels and SMTP configuration errors.

**Comment by moxious** [comment]
**Summary**: User tonypowa is experiencing an issue with Grafana Altering; after configuring SMTP to send emails, an error with messages 'Missing receiver' and 'Missing group labels' occurs upon sending a test notification. The issue remains open with one comment, no assignees or projects, and is described in detail on how it can be reproduced.

**Comment by moxious** [comment]
**Elaboration**:


Hi @tonypowa! 

Thank you for reporting the issue with Grafana Alerting and taking the time to provide some details. To help us better understand the problem and get to the bottom of this, we need a bit more information. 

1. Can you ensure that the links to the error screenshots are correct? It seems that they might not be pointing to the correct URLs as they should typically end with `.png` or `.jpg`. A working link to the screenshots would be useful to visualize the errors. 

2. Could you describe what the error messages say in the screenshots? This would be helpful for those working on environments where images might not load properly or those who use screen readers. 

3. After modifying the `grafana.ini` configuration, did you remember to restart the Grafana service to apply the changes?

4. Could you check whether the SMTP settings in the `grafana.ini` file match exactly with your email service provider's required settings? Occasionally, small discrepancies can cause issues.

5. Have you tested the SMTP settings independent of Grafana to ensure that the server is reachable and credentials are correct? For example, attempting to send an email via a command-line tool.

6. Are there more detailed logs around the error that occurred in the Grafana log file? If so, please share the relevant log excerpts surrounding the error.

7. Is there any configuration related to alert routing in your Grafana setup that might be missing or misconfigured?

Once you provide us with this information, we will be in a better position to help resolve the issue. Thanks again!

Best regards,
[Your Name]
