### ISSUE TITLE
Grafana Generic OIDC Role mapping no change

### ISSUE THREAD

**Issue by tonypowa** [moxious/triage#250]
### What happened?

We are using Grafana 9.5.2 with Generic OIDC configured, AAD is the IDP.

User A was in the group of Editor on AAD and the role maaping is working fine. However, when we deleted him from the Editor group, he still has the Editor permission when logged into Grafana.

### What did you expect to happen?

I hope the role could be switched to Viewer.

### Did this work before?

No, this is the first time we tried.

### How do we reproduce it?

1. Set up Generic OIDC with any IDP (we are using AAD)

2. Log into Grafana to check the role mapping

3. Remove the user from IDP and log into Grafana again to check the role

Here is the config screenshot:

![image](https://github.com/grafana/grafana/assets/19278537/02f88140-2103-4bab-bd90-8e8b6bca0aaa)

### Is the bug inside a dashboard panel?

No.

### Environment (with versions)?

Grafana: 9.5.2 (commit: cfcea75916, branch: HEAD)

OS: RHEL 8.8

Browser: Chrome/IE

### Grafana platform?

A downloaded binary

### Datasource(s)?

Prometheus

**Comment by tonypowa** [comment]
This issue is a test copy of an issue in another repo.  Original issue: https://github.com/grafana/grafana/issues/#80694

**Comment by moxious** [comment]
**Summary**: Grafana 9.5.2 with Generic OIDC has a role mapping issue where a user removed from the Editor group in AAD still retains Editor permissions in Grafana, instead of being downgraded to Viewer.

**Comment by moxious** [comment]
Hello @tonypowa, it seems like your issue may be related to the **Identity and Access project** as it involves user role mapping with Generic OIDC and authentication issues. Aligning user roles in Grafana with identity providers like AAD typically falls under identity and access management.

**Comment by moxious** [comment]
**Elaboration**:


Thank you for submitting the issue with detailed steps and environment information. It seems like there might be a caching issue or a delay in synchronization between AAD and Grafana. However, we need a bit more information to fully understand and troubleshoot the problem. Could you please provide the following details?

1. After removing User A from the Editor group on AAD, did you check the group memberships directly on AAD to confirm the changes were effective there?
2. How long did you wait after removing the user from the Editor group before checking the permissions in Grafana? Sometimes these changes can take time to propagate.
3. Can you confirm if you've configured any cache settings within Grafana's OIDC setup that might affect how frequently it updates the role information?
4. Could you provide the relevant config sections related to role mapping in your Grafana OIDC config? Please make sure to redact any sensitive information.
5. Have you tried a hard refresh or clearing the cache in your browser after the change in the user’s group membership?
6. Is there a token refresh or expiration policy set in place which might require the user to re-authenticate for changes to take effect?
7. Were there any error messages or logs that you can share when the user logs back into Grafana after their role should have changed?

Any additional details or logs you could share would be greatly appreciated and help us address your issue more accurately. Thank you!
