### ISSUE TITLE
massive grafana rules performance

### ISSUE THREAD

**Issue by tonypowa** [moxious/triage#255]
### What happened?

The alert generator evaluates all alert rules on all instances. when there are massive number of alert rules, it will take a long time to evaluate all of them. resulting in a long delay in alerting. how can we improve the performance of alerting?

### What did you expect to happen?

A way to horizontally scale the alert generator? or sharding by group?

### Did this work before?

no

### How do we reproduce it?

set massive number of alert rules

### Is the bug inside a dashboard panel?

no

### Environment (with versions)?

Grafana:

OS:

Browser:

### Grafana platform?

A downloaded binary

**Comment by tonypowa** [comment]
This issue is a test copy of an issue in another repo.  Original issue: https://github.com/grafana/grafana/issues/#80788

**Comment by moxious** [comment]
**Summary**: Issue #255 OPEN: User tonypowa reports performance issues with Grafana's alert generator taking a long time to evaluate a massive number of alert rules, resulting in delayed alerts. They are seeking solutions for horizontal scaling or sharding by group to improve performance.
