### ISSUE TITLE
Dashboards: "Expand results" toggle gets applied to the wrong pane when in split view

### ISSUE THREAD

**Issue by tonypowa** [moxious/triage#264]
### What happened?

When I split an Explore view, if I click the "Expand results" toggle on the right pane, it takes action on the left pane only. Clicking on the left one works on the left one. So I don't see a way to toggle "Expand results" except on the first pane. 

### What did you expect to happen?

When I split an Explore view I expect it to toggle the one I clickedd

### Did this work before?

First time I tried

### How do we reproduce it?

1. Go to Explore view

2. Write a query with results in the first pane

3. Spit panes and write another query

4. Click toggle results on the right pane

### Is the bug inside a dashboard panel?

In the Explore view, not really in a panel

### Environment (with versions)?

Grafana: Grafana v9.5.13 (802385ecac) on Azure Managed Grafana

OS: MacOs

Browser: Edge Version 122.0.2325.0 (Official build) Dev (x86_64)

### Grafana platform?

Other

### Datasource(s)?

Prometheus

----

Initial state:

![image](https://github.com/grafana/grafana/assets/1774478/bc93fe1b-79a5-4b6b-9e85-fcde5f6cf9f9)

click on **right** Expand toggle

<img width="1262" alt="image" src="https://github.com/grafana/grafana/assets/1774478/d370a52e-54b0-41f9-9d8c-a74bb00d8007">

**Comment by tonypowa** [comment]
This issue is a test copy of an issue in another repo.  Original issue: https://github.com/grafana/grafana/issues/#80833

**Comment by moxious** [comment]
**Summary**: Issue #264, opened by tonypowa, describes a problem in Grafana where the 'Expand results' toggle in split Explore view affects the left pane regardless of which pane's toggle is clicked, preventing the expansion of the right pane's results. This behavior deviates from the expected functionality and occurs on Grafana v9.5.13 using MacOS and Edge browser.

**Comment by moxious** [comment]
Hi @tonypowa, thank you for bringing this to our attention. It seems like an issue specific to the Explore functionality. We suggest associating this issue with the **Explore project**, as it is the best fit for handling UI quirks within the Explore views. The team managing that project would be best equipped to address this problem.

**Comment by moxious** [comment]
**Elaboration**:


Hello @tonypowa, thank you for reporting the issue with the 'Expand results' toggle in Grafana's split view. 🛠️ To help us investigate this problem more thoroughly, could you please provide us with the following additional information? 

1. **Console Logs:** Are there any errors showing up in the browser console when you attempt to click the 'Expand results' toggle in the second pane? If yes, could you please copy and paste them or include a screenshot of the console? 

2. **Network Requests:** Sometimes, issues like these may relate to failed network requests. Can you open your browser's developer tools to the Network tab and observe if any requests fail when you attempt to toggle the expansion? 

3. **Exact Steps:** To ensure we're doing exactly what you are, could you list the steps you're taking in greater detail or provide a screen recording of the issue occurring? This might help us catch any nuances in the reproduction process. 

4. **Extension Conflict:** Sometimes, browser extensions can cause unexpected behavior in web applications. Could you try reproducing this issue in an incognito window or with extensions disabled? 

5. **Browser Compatibility:** Have you tried this on any other browser to see if the issue persists across different browsers? 

Once we have this additional information, we'll be better equipped to troubleshoot your issue further. Looking forward to your response!
