### ISSUE TITLE
Query regex not working properly with version>=10.2.3

### ISSUE THREAD

**Issue by tonypowa** [moxious/triage#270]
### What happened?

When query with field value contains a variable, it retrieved wrong field values to display. For example:

field =~ /$variable-xxxxxx/

### What did you expect to happen?

Hope to fix this issue in next release

### Did this work before?

Version <= 10.2.2 does not have this problem

### How do we reproduce it?

1. create a influxDB measurement with different field values, for example "a_output_values", "b_output_values", "c_output_values", "a_log_values", "b_log_values", "c_log_values", 

2. create a variable called 'prefix' with values of "a", "b", "c"

3. when query fieldName =~ /^$prefix_output/, it displays all 6 fields rather than 3

### Environment (with versions)?

Grafana: 10.2.3, 10.3.1

OS: MacOS 14.2.1

Browser: Chrome 120.0.6099.234 (Official Build) (arm64)

### Grafana platform?

Docker

**Comment by tonypowa** [comment]
This issue is a test copy of an issue in another repo.  Original issue: https://github.com/grafana/grafana/issues/#81127

**Comment by moxious** [comment]
**Summary**: The issue, opened by tonypowa, highlights a problem with regex queries in Grafana versions >=10.2.3 that returns incorrect field values when variable placeholders are used, a bug not present in earlier versions. The expectation is for a fix in an upcoming release, alongside a reproducible test case provided.

**Comment by moxious** [comment]
Hi @tonypowa, it seems like the issue you're experiencing might be related to how Grafana is handling regex queries with variables in Grafana itself. This could be an issue with the Frontend platform or the Grafana Metrics project, depending on the specifics of the bug. You're mentioning a version (10.2.3 and above) which indicates this could be a regression in a recent update. It might be worth checking if this issue persists in the latest version, or if there have been any related changes noted in the release notes. 

Can you also specify if the variable substitution and regex query are being used within a particular Grafana panel or datasource plugin? That might help to narrow down the exact project this should be associated with.

**Comment by moxious** [comment]
**Elaboration**:


Hi @tonypowa, thank you for reporting the issue with the regex query handling in Grafana. To help us further investigate this issue, could you please provide a bit more information? Here are some clarifying questions:

1. Can you confirm if the issue persists across different browsers or is isolated to Chrome?

2. Is there any error message or warning in the Grafana UI or browser console when the issue occurs?

3. Could you provide screenshots or recordings of the issue, especially showing the queries and the resulting behavior?

4. Have you tried escaping the variable in the regex differently, e.g., `field =~ /${variable}-xxxxxx/`, to see if it affects the outcome?

5. Is there any additional configuration in Grafana that might be relevant, such as template variable settings or datasource specific settings?

6. You mentioned using Docker; could you share the Docker run command or Docker-compose file, in case there's something in the container setup that could be affecting this?

7. For the datasource question that is not answered, could you specify which datasource you're using (e.g., InfluxDB version)? This might be relevant in case there's a known issue with the specific version.

8. Are there any logs from Grafana when you encounter the issue that might provide more insight?

9. Lastly, if possible, a minimal reproducible example (like a stripped-down dashboard JSON that demonstrates the problem) could be very useful for diagnosing the issue without needing to replicate your full environment.

Once again, thank you for your contribution, and we look forward to resolving this issue together. If it's easier to provide the above information in multiple steps or batches, that's perfectly fine too.
