### ISSUE TITLE
Grafana Alerting: Alerts duplicate causing multiple alerts and resolution messages

### ISSUE THREAD

**Issue by tonypowa** [moxious/triage#275]
### What happened?

Hey everyone, I’m looking for some advice.

I get multiple notification for the same alert. I've tried recreating the alert with just the query and very basic settings but the same issue persisted. At one point I was getting 4 alerts but usually it's just 2. 

I have a loki alert that looks for the word “failed” in logs. It’s got a 30 minute window to look (the job runs every 30 min)

this is the query

count_over_time({instance="prod-backend", app="patientCache"} |= `Failed`[5m])

the history shows the duplication

![image](https://github.com/grafana/grafana/assets/103214468/8c85d9d4-9497-42c6-9f92-25034c671040)

### What did you expect to happen?

I expect that when you configure one alert, show preview and it says firing, that the alert would just appear once, not multiple times and also it's not grouped for those multiple, like others firing alerts would

### Did this work before?

I'm not sure

### How do we reproduce it?

1. Deploy grafana with helm chart on kubernetes (chart v7.0.3)

2. Create Loki alert

3. Multiple alerts

### Environment (with versions)?

Grafana: helm chart on k8s (7.0.3)

OS: N/A

Browser: N/A

### Grafana platform?

Kubernetes

### Datasource(s)?

loki

**Comment by tonypowa** [comment]
This issue is a test copy of an issue in another repo.  Original issue: https://github.com/grafana/grafana/issues/#81198

**Comment by moxious** [comment]
Hi @tonypowa, thank you for bringing this to our attention. It sounds like an issue related to how alerts are processed within Grafana, and the Alerting team would be the best to provide assistance with this. I'll label this issue for the **Alerting project** so it can be properly tracked and handled by the team specializing in alerting functionalities.

**Comment by moxious** [comment]
**Elaboration**:


Hello @tonypowa,

Thank you for reaching out with the alert duplication issue you're encountering. To better assist you, I have a few questions that can help pinpoint the cause of this behavior:

1. Can you confirm if the alert rule you've set up is the only one for the specific query? Sometimes there could be multiple rules with similar configurations.
2. Could you provide a bit more detail on the notification settings? Specifically, the configuration of the notification channels and if you're using any grouping, deduplication, or silence policies.
3. Have you noticed any patterns in when the duplication occurs, like during specific times of the day, certain load conditions, or after specific actions such as deployments or updates?
4. It would be useful to have a screenshot of the history of the alerts from Grafana that shows the duplication. The link in your issue description seems to be incomplete or broken. Could you please provide a working link or upload the image again?
5. Can you provide the logs from Grafana around the time the alerts are fired and duplicated? These could contain useful information about what is happening internally.
6. Could you share the output of the `helm get values grafana` command (if you can do so without disclosing sensitive information), so we can see if there is any specific configuration that could be leading to this issue?

Any additional details you can provide will be immensely helpful in diagnosing the issue. Including exact steps you've followed, any changes from default configurations, and any observations you have about the problem's behavior.

Thank you for your cooperation, and we hope to resolve this issue promptly.

Best Regards,
The Grafana Team

**Comment by moxious** [comment]
**Summary**: User tonypowa opened an issue reporting duplicate alert notifications in Grafana when setting up a Loki alert to detect the term 'failed' in logs. Despite having simple settings, the system sends out multiple notifications for the same alert, typically two but sometimes as many as four, even though the expectation is a single alert per event.
