### ISSUE TITLE
Alerts: Graph does not display

### ISSUE THREAD

**Issue by tonypowa** [moxious/triage#289]
### What happened?

User created a new dashboard, Attempted to create a new alert for the dashboard. When the query was executed data was returned but the UI only shows a table view with the first data point value from the JSON data section. 

### What did you expect to happen?

User should have seen a graph of the resulting data. 

### Did this work before?

Yes prior to Grafana version 10.3.1

### How do we reproduce it?

See what happened section

### Environment (with versions)?

Grafana: 10.3.1

OS: Linux Centos 7

Browser: Chrome

### Grafana platform?

A package manager (APT, YUM, BREW, etc.)

### Datasource(s)?

TSDB

**Comment by tonypowa** [comment]
This issue is a test copy of an issue in another repo.  Original issue: https://github.com/grafana/grafana/issues/#82027

**Comment by moxious** [comment]
**Summary**: Issue #289, titled 'Alerts: Graph does not display', reports a problem where a user expects to see a graph of query results on a new dashboard alert in Grafana 10.3.1, but only sees a table with a single data point. This is a regression since it worked in earlier versions.

**Comment by moxious** [comment]
**Elaboration**:


Hello @tonypowa, thank you for the issue report. Your initial description provides a good starting point, but to help us better understand and replicate the problem, we’ll need a little more information. Could you please provide the following details? :

- Could you give us the exact steps to reproduce the issue from creating a new dashboard to the point where the alert graph doesn't display properly? A step-by-step guide would be very helpful.
- When you mentioned that only a 'table view with the first data point' is shown, could you attach a screenshot of the UI, showing both the table view and any error messages or console outputs in the browser's developer tools?
- Have you customized the panel in any way that might affect the rendering of the graph (such as panel plugins or specific visualization settings)?
- Do you receive any error messages in the Grafana backend logs when attempting to view the graph?
- Has the issue been noticed in other browsers or on other operating systems as well?
- If there's any panel JSON configuration that you can share without exposing sensitive information, that could also be very useful.

Providing this additional information would help us to diagnose and address the issue more efficiently.

Thanks again for your contribution to the community!

**Comment by moxious** [comment]
Hello @tonypowa, it looks like your issue is related to the alerting feature of Grafana. Specifically, the problem seems to be with the alert graph visualisation. Therefore, I believe the best project for this issue is the **Alerting project**.

Could you please check if there are any console errors in the browser when you try to view the graph? Furthermore, it would be helpful if you could share the panel JSON that you're using. This will aid the team in reproducing the issue.

Meanwhile, I'll label this issue to get the attention of the Alerting project team.
