### ISSUE TITLE
InfluxDB data source 405 error

### ISSUE THREAD

**Issue by tonypowa** [moxious/triage#294]
### What happened?

When attempting "Save & Test" I get this error:

ERROR: flightsql: rpc error: code = Unknown desc = unexpected HTTP status code received from server: 405 (Method Not Allowed); transport: received unexpected content-type "text/html"

I am following the instructions here:

https://docs.influxdata.com/influxdb/cloud-serverless/process-data/visualize/grafana/

and here:

https://www.influxdata.com/blog/official-influxdb-v3-data-source-grafana-released/

### What did you expect to happen?

A successful connection

### Did this work before?

No

### How do we reproduce it?

1. Create an InfluxDB using the tutorial e.g. <influx home>/new-user-setup/python

2. Follow the instructions https://www.influxdata.com/blog/official-influxdb-v3-data-source-grafana-released/

### Environment (with versions)?

Grafana: v10.4.0-65875 (b758b91e84)

OS: Mac

Browser: Chrome

### Grafana platform?

I use Grafana Cloud

### Datasource(s)?

InfluxDB

**Comment by tonypowa** [comment]
This issue is a test copy of an issue in another repo.  Original issue: https://github.com/grafana/grafana/issues/#82120

**Comment by moxious** [comment]
Hi @tonypowa, it seems like this issue might be related to the integration with InfluxDB as a datasource in Grafana. I would recommend redirecting this issue to the **AWS Datasources project** as the InfluxDB datasource is typically bundled there, despite the cloud nature of your setup. However, if this is specifically related to a cloud serverless setup, the **Partner datasources project** might be more appropriate. Please specify whether the issue happens with a self-hosted InfluxDB instance or with InfluxDB cloud to help the team triage the issue effectively.

**Comment by moxious** [comment]
**Summary**: User tonypowa is encountering a 405 Method Not Allowed error when attempting to 'Save & Test' an InfluxDB data source on Grafana Cloud following official documentation, with no previous success on establishing a connection.

**Comment by moxious** [comment]
**Elaboration**:


Hello @tonypowa, thank you for reaching out and providing the initial details on the issue you are facing with connecting InfluxDB as a data source in Grafana. We want to help you resolve this, but to proceed we need a bit more information. Could you please provide the following additional details to help us understand and reproduce the issue more accurately? 

1. Can you confirm if you've set up any proxy or network configurations that could potentially impact the communication between Grafana and InfluxDB?
2. Please double-check and ensure that the endpoint URL and other connection details entered in Grafana match exactly what's required by InfluxDB as per their documentation.
3. Have you modified any headers or added specific settings in the configuration of the InfluxDB datasource within Grafana?
4. Do you observe any log outputs on the InfluxDB server side when the 405 error occurs, and can you share them here (ensuring you redact any sensitive information)?
5. Could you provide the complete request URL (without credentials or sensitive information) that you're using when you encounter this error?
6. Are you able to access the InfluxDB API directly outside of Grafana (e.g., via curl or Postman) without encountering the same error?

Additionally, a step-by-step reproduction would be invaluable. If you could share detailed steps that include any terminal commands you are running, or screenshots of the configuration screens with sensitive data blurred or omitted, it would assist us hugely in diagnosing the problem.

Once we have this information, we'll be able to delve deeper into the issue and work towards a solution. Thank you!
