### ISSUE TITLE
Grafana Annotations persist across graphs made from different variables

### ISSUE THREAD

**Issue by tonypowa** [moxious/triage#296]
##### Is there a way for Grafana to only show the annotation for a particular panel for that set of variables. I have 1 panel that changes based on some variables selected. Can I make it such that if I make an annotation for one variable, it doesn't show up on the other. 

<img width="755" alt="Screenshot 2024-02-13 at 2 23 59 PM" src="https://github.com/grafana/grafana/assets/106616061/74e74f03-8d88-4e86-a1e8-7d85eb23acf1">

**Comment by tonypowa** [comment]
This issue is a test copy of an issue in another repo.  Original issue: https://github.com/grafana/grafana/issues/#82394

**Comment by moxious** [comment]
Hi @tonypowa! It sounds like you're looking for panel-specific annotations in Grafana, which pertain to the usability of annotations within dashboards. This issue would be best suited for the **Dashboards Sharing squad** project. The team involved with that project can more appropriately provide insights or consider feature requests related to dashboard functionality.

**Comment by moxious** [comment]
**Summary**: The issue, still open and reported by tonypowa, involves Grafana annotations being displayed across different panels despite panel variables being changed. The author is looking for a solution to restrict annotations to be specific to selected panel variables.
