### ISSUE TITLE
UI: Text Panel disappears on Safari

### ISSUE THREAD

**Issue by tonypowa** [moxious/triage#303]
### What happened?

Hello,

Not sure how to describe this issue but i have a text panel on the same line with other panels (Table for example)

When i hover on table rows Text panel dissapear

### What did you expect to happen?

Text panel remains visible

### Did this work before?

It worked on 10.1

### How do we reproduce it?

1.Create a table panel

2.Create a text panel

3.Hover on Table rows

### Environment (with versions)?

Grafana:10.3.1

OS: Sonoma 

<img width="1718" alt="Screenshot 2024-02-17 at 01 19 53" src="https://github.com/grafana/grafana/assets/13196005/5b3607ea-c4ea-4539-8999-e73d8bcf3c03">

<img width="1706" alt="Screenshot 2024-02-17 at 01 20 21" src="https://github.com/grafana/grafana/assets/13196005/1117c01e-0538-430e-a2a3-b727337f9ead">

14.2.1 (23C71)

Browser: Safari

### Grafana platform?

Kubernetes

**Comment by tonypowa** [comment]
This issue is a test copy of an issue in another repo.  Original issue: https://github.com/grafana/grafana/issues/#82975

**Comment by moxious** [comment]
Hi @tonypowa, 

Thank you for bringing this issue to our attention. It seems like it could be a problem specific to the Safari browser and the interaction between table and text panels. I'm tagging this for the **Frontend Platform project**, as they would be the best team to handle UI rendering issues across different browsers.

**/label** `frontend-platform`

The team will look into this and follow up with you for any updates or additional information required.

**Comment by moxious** [comment]
**Elaboration**:


Thank you for reporting the issue, tonypowa. To help us better understand and resolve the problem you're encountering with the text panel disappearing in Safari, we would appreciate some additional information. Could you please provide the following details? 

- **Steps to Reproduce:** Are there any specific steps or actions that consistently cause the text panel to disappear when you hover over the table rows? If so, please list them in as much detail as possible. 

- **Safari Version:** Please confirm the version of Safari you are using. 

- **User Interface Screenshot:** While you provided screenshots, it's unclear whether they display before or after the issue occurs. Could you clearly label them as 'before' and 'after', or provide a short video capture showing the issue in action? 

- **Console Errors:** Open the browser's developer tools (usually F12 or Command+Option+I on Mac) and check the console for any error messages when the issue occurs. Please include any errors you see. 

- **Comparison Information:** You mentioned that this worked in Grafana 10.1 but not in 10.3.1. Can you access the older version and provide a screenshot or details of the behavior there for comparison? 

- **Data Source Configuration:** Even though you didn't mention issues with the data source, sometimes panel behavior can be influenced by the backend. If possible, could you provide a summary of how the data source is set up? 

Following these additional clarifications, we'll be in a much better position to triage and address the issue. Thank you for your collaboration and for contributing to the community!
