### ISSUE TITLE
Incorrect data in the pop-up window

### ISSUE THREAD

**Issue by tonypowa** [moxious/triage#304]
### What happened?

When you hover over a row at the bottom of the visualization and move the cursor to the right, a pop-up window may show data from another row

> 

### What did you expect to happen?

When you hover the cursor over a row at the bottom of the visualization and move the cursor to the right, the data of the rowthat is selected is displayed in a pop-up window

### Did this work before?

I don't know

### How do we reproduce it?

1. Make State timeline visualisation with Transform Partition by values - Field Name.

2. Hover coursor on one of the last two rown and moove cursor right.

### Is the bug inside a dashboard panel?

[debug-Panel-19.02.2024 12_51_45.json.txt](https://github.com/grafana/grafana/files/14326096/debug-Panel-19.02.2024.12_51_45.json.txt)

### Environment (with versions)?

Grafana: Grafana v10.0.1

OS: Linux

Browser: Chrome, Edge

### Grafana platform?

None

**Comment by moxious** [comment]
**Summary**: Issue #304, opened by tonypowa, is about a bug in a visualization where hovering over a row at the bottom and moving the cursor to the right causes the pop-up window to display data from a different row, instead of the data from the selected row. The issue is currently OPEN and has 1 comment.

**Comment by moxious** [comment]
Hello @tonypowa, it seems like this issue might be related to the core functionality of the data visualization in Grafana. The best project that aligns with this issue appears to be the **DataViz project**. I'll label this for the DataViz team to take a look.

/cc @grafana/dataviz-team

**Comment by moxious** [comment]
**Elaboration**:


Thank you for providing a good overview of the issue you're experiencing. To help us better understand and address the problem, could you please supply additional information? Here are some requests for further details that would be greatly beneficial:

- **Screenshots**: Could you provide a screenshot or a screen recording of the issue occurring? This visual context can often be very helpful in diagnosing the problem.

- **Browser Developer Console**: Are there any errors showing up in the browser's developer console when the issue happens? If so, please copy and paste them or add a screenshot of these errors.

- **Grafana Logs**: Are there any relevant logs from Grafana that would help us understand what's happening when the pop-up shows incorrect data? Checking your Grafana server logs around the time the issue occurs could provide useful insights.

- **Additional Replication Details**: Can you ensure that the issue consistently occurs at the bottom two rows only or does it appear sporadically on other rows as well? Also, are you able to reproduce this issue on a different dashboard or with different data?

- **Plugin Information**: If applicable, what version of the State timeline plugin are you using? Has it been updated recently?

We appreciate your cooperation in helping us diagnose and fix this issue. Your participation in the community helps improve the experience for everyone using the software!
