### ISSUE TITLE
Alert rules unreliable

### ISSUE THREAD

**Issue by tonypowa** [moxious/triage#307]
### What happened?

Some alert rules don't display all matching instances. At the moment no real pattern can be identified. This only applies to some rules and not all. 

<img width="941" alt="image" src="https://github.com/grafana/grafana/assets/32478819/8b227dc1-fc29-4539-b3be-69bf96eea667">

### What did you expect to happen?

All matching instances should be displayed

### Did this work before?

Not sure

### How do we reproduce it?

1. Select firing Alert Rule

2. Check matching instances

3. Detect difference between instances and Query & Results

### Is the bug inside a dashboard panel?

This also has impact on the Alert List

### Environment (with versions)?

Grafana: Grafana v10.3.3 (252761264e)

OS: Mac OS X

Browser: Firefox

### Grafana platform?

Kubernetes

### Datasource(s)?

Prometheus (via Thanos)

**Comment by tonypowa** [comment]
This issue is a test copy of an issue in another repo.  Original issue: https://github.com/grafana/grafana/issues/#83364

**Comment by moxious** [comment]
Hi @tonypowa, it looks like your issue might be related to the Alerting system in Grafana. I'm directing this for the attention of the **Alerting project** team. They will be best equipped to help identify and resolve issues with alert rules not displaying all matching instances, especially when integrated with Prometheus data sources.

As you wait for a response, it might be helpful to check the Grafana [Alerting documentation](https://grafana.com/docs/grafana/latest/alerting/) (if you haven't already) to ensure that the configuration aligns with best practices.

**Comment by moxious** [comment]
**Elaboration**:


### Clarification Needed on Alerting Issue

Hi @tonypowa, 

First of all, thank you for taking the time to report this issue. We appreciate your contribution to the community.

While your report provides a good general understanding of the issue, there are a few additional details that would help us investigate further and find a resolution:

1. **Pattern Observation:** 
 When you mention that no real pattern can be identified, have you noticed any common factors among the rules that don’t display all matching instances? Any information on the characteristics of the affected rules can be crucial.

2. **Steps for Reproduction:** 
 Could you provide a more detailed explanation or a step-by-step guide for how to reproduce the issue, including sample data or exact queries you're using? This helps ensure we can experience the issue under the same conditions.

3. **Previously Functioning:** 
 If you're unsure whether this worked before, it may be helpful to check if an older version of Grafana does not exhibit the same problem, if that is feasible.

4. **Image Accessibility:** 
 It seems that the link to the image you provided does not work. Could you please re-upload the screenshot? A working image can give us visual context.

5. **Error Logs:** 
 Are there any error messages in the Grafana logs when the issue occurs? Providing logs can help diagnose underlying problems more accurately.

6. **Alert Configuration:** 
 Sharing the configuration of a problematic alert rule (with sensitive data redacted) could provide insights into potential misconfigurations or bugs.

7. **Version Confirmation:** 
 Can you confirm the Grafana version is correct, as the provided version format seems unconventional?

Once we have these additional details, we'll be in a much better position to understand and address the issue you're facing.

Thank you!
