### ISSUE TITLE
Alert manager: Authorization header is missing

### ISSUE THREAD

**Issue by tonypowa** [moxious/triage#308]
### What happened?

We use the Prometheus Datasource. We use a custom auth wrapper on top of Prometheus that only accepts oauth2 tokens. When creating an alert in the alert manager. Everything works fine. The token is used for all the dashboards and alert rule preview. When saving the Alert Rule, all rules get the same status: No data. In the backend i see that all requests from alert manager get a 403 with the message: "authorization header is missing"

### What did you expect to happen?

That the alert manager backend sends the request with a forwarded OAuth Identity

### Did this work before?

I don't know. This is the first time we implement the Alert Manager

### How do we reproduce it?

1. Create a Prometheus datasource

2. Enable "Forward OAuth Identity"

3. Create a Alert Rule

4. Wait a while

5. Get a NoData label

### Environment (with versions)?

Grafana: 10.3.1

OS: Kubernetes

Browser: Firefox

### Grafana platform?

Kubernetes

### Datasource(s)?

Latest embedded Prometheus datasource

**Comment by tonypowa** [comment]
This issue is a test copy of an issue in another repo.  Original issue: https://github.com/grafana/grafana/issues/#83365

**Comment by moxious** [comment]
**Summary**: User tonypowa reports an issue where the alert manager in Grafana fails to forward the OAuth Identity causing a `403 authorization header is missing` error, leading to all alert rules having a status of 'No data' on a Kubernetes environment.

**Comment by moxious** [comment]
Hello @tonypowa, it sounds like this issue pertains to the handling of OAuth tokens and the Alerting system within Grafana. I believe the most appropriate team to look at this would be the **Alerting project**. They specialize in the functionality surrounding alert rules and notifications, which appears to be at the core of the problem you're facing with the Alert Manager's authorization mechanism.
