### ISSUE TITLE
Update dependency webpack-dev-server to v5

### ISSUE THREAD

**Issue by tonypowa** [moxious/triage#311]
[![Mend Renovate](https://app.renovatebot.com/images/banner.svg)](https://renovatebot.com)

This PR contains the following updates:

| Package | Change | Age | Adoption | Passing | Confidence |
|---|---|---|---|---|---|
| [webpack-dev-server](https://togithub.com/webpack/webpack-dev-server) | [`4.15.1` -> `5.0.2`](https://renovatebot.com/diffs/npm/webpack-dev-server/4.15.1/5.0.2) | [![age](https://developer.mend.io/api/mc/badges/age/npm/webpack-dev-server/5.0.2?slim=true)](https://docs.renovatebot.com/merge-confidence/) | [![adoption](https://developer.mend.io/api/mc/badges/adoption/npm/webpack-dev-server/5.0.2?slim=true)](https://docs.renovatebot.com/merge-confidence/) | [![passing](https://developer.mend.io/api/mc/badges/compatibility/npm/webpack-dev-server/4.15.1/5.0.2?slim=true)](https://docs.renovatebot.com/merge-confidence/) | [![confidence](https://developer.mend.io/api/mc/badges/confidence/npm/webpack-dev-server/4.15.1/5.0.2?slim=true)](https://docs.renovatebot.com/merge-confidence/) |

---

> [!WARNING]
> Some dependencies could not be looked up. Check the Dependency Dashboard for more information.

---

### Release Notes

<details>
<summary>webpack/webpack-dev-server (webpack-dev-server)</summary>

### [`v5.0.2`](https://togithub.com/webpack/webpack-dev-server/blob/HEAD/CHANGELOG.md#502-2024-02-16)

[Compare Source](https://togithub.com/webpack/webpack-dev-server/compare/v5.0.1...v5.0.2)

### [`v5.0.1`](https://togithub.com/webpack/webpack-dev-server/blob/HEAD/CHANGELOG.md#501-2024-02-13)

[Compare Source](https://togithub.com/webpack/webpack-dev-server/compare/v5.0.0...v5.0.1)

### [`v5.0.0`](https://togithub.com/webpack/webpack-dev-server/blob/HEAD/CHANGELOG.md#500-2024-02-12)

[Compare Source](https://togithub.com/webpack/webpack-dev-server/compare/v4.15.1...v5.0.0)

[Migration Guide and Changes](https://togithub.com/webpack/webpack-dev-server/blob/master/migration-v5.md).

##### Bug Fixes

- replace `::` with `localhost` before openBrowser() ([#&#8203;4856](https://togithub.com/webpack/webpack-dev-server/issues/4856)) ([874c44b](https://togithub.com/webpack/webpack-dev-server/commit/874c44b072d55fe42a29d366dbe1c71ca3a94db4))
- **types:** compatibility with `@types/ws` ([#&#8203;4899](https://togithub.com/webpack/webpack-dev-server/issues/4899)) ([34bcec2](https://togithub.com/webpack/webpack-dev-server/commit/34bcec242b8bc64c26e9455a8fd5781a59fbcf24))

</details>

---

### Configuration

📅 **Schedule**: Branch creation - At any time (no schedule defined), Automerge - At any time (no schedule defined).

🚦 **Automerge**: Disabled by config. Please merge this manually once you are satisfied.

♻ **Rebasing**: Whenever PR becomes conflicted, or you tick the rebase/retry checkbox.

🔕 **Ignore**: Close this PR and you won't be reminded about this update again.

---

 - [ ] If you want to rebase/retry this PR, check this box

---

This PR has been generated by [Mend Renovate](https://www.mend.io/free-developer-tools/renovate/). View repository job log [here](https://developer.mend.io/github/grafana/grafana).

**Comment by tonypowa** [comment]
This issue is a test copy of an issue in another repo.  Original issue: https://github.com/grafana/grafana/issues/#83258

**Comment by moxious** [comment]
**Summary**: Issue #311 is open and discusses updating the webpack-dev-server dependency from version 4.15.1 to 5.0.2, with details on age, adoption, passing rates, and confidence levels for the upgrade.
