### ISSUE TITLE
Dashboards: multi value variables with backslash can't be used in KQL query with "in"

### ISSUE THREAD

**Issue by tonypowa** [moxious/triage#316]
### What happened?

If I create a variable that is multi value and it has several items selected without a backslash in the values I can reference that variable in KQL queries using an "in" like this:

`| where ColumnName in ($VarName)`

However, if the column/variable has backslashes this does not work. Nor does using any of the options (that I've tried anyway), such as `${VarName:regex}`.

I have tried a number of things to try to get this to work but can't seem to figure anything out that would work.

### What did you expect to happen?

I would expect to be able to have an easy way to do something like `| where ColumnName in ($VarName)` or `| where ColumnName in (${VarName:someoptionhere})`

### Did this work before?

I don't know.

### How do we reproduce it?

1. create a variable in a dashboard that queries the distinct values in a table - where the column contains a backslash such as a filepath. Some simple values such as `Something\1234`, `Bob\Loblaw`, `Hello\World` would also work

2. Define the variable as multi-value and include the All option

3. create a visual that uses kql (ADE connection) to query the same table (or one you create with dummy values) that the variable does and in the query do something like `TableName | where Column in ($VarName)` (or some other option of that)

4. if you don't get an error I'd be surprised...but if you don't you likely won't get any data (even though the default at this point is "All" which should query everything in the table.

You can compare to something without a backslash by doing the same steps but using a column with values without a backslash.

### Environment (with versions)?

Grafana: Azure Managed Grafana (version 9.5.16)

OS: Windows 11

Browser: Microsoft Edge

### Grafana platform?

Other

### Datasource(s)?

Azure Data Explorer

**Comment by moxious** [comment]
**Summary**: Issue #316 remains open where multi-value dashboard variables containing backslashes cannot be used in KQL 'in' queries. Attempted workarounds and special options like regex substitution have failed, and expected functionality to query data as in `| where ColumnName in ($VarName)` is not working as anticipated when backslashes are involved. Reproduction steps involve dashboard variables querying distinct column values with backslashes and using them in KQL queries.

**Comment by moxious** [comment]
**Elaboration**:


### Request for additional information
Hi @tonypowa, thank you for reporting the issue with using multi-value variables containing backslashes in KQL queries within the Grafana dashboards.

To help us better understand and address the issue, could you please provide the following additional information?

- **Error Messages**: Are there any error messages displayed when the query fails? If so, could you please share the exact message or a screenshot?

- **Query Samples**: Could you provide specific examples of the KQL queries that aren't working? Including one that demonstrates the failure when using a variable with backslashes and one with non-backslashed values that works as expected.

- **Variable Configuration**: Can you share the configuration options you've set for your multi-value variable, especially any custom settings related to regex or formatting?

- **Reproduction Steps Detail**: While you've given an overview of the steps to reproduce, ensuring every detail is clear can be crucial. Could you confirm if the column name matches the variable name exactly, and if there's any additional query syntax that might be relevant?

- **Previous Versions**: If you're not sure whether this worked in the past, are you able to test on a previous version of Grafana, or is there a version where you know this functionality was working as expected?

- **Workarounds Attempted**: Have you found or tried any potential workarounds, even if they were not successful? For instance, manually replacing backslashes or using a different query format?

Your cooperation is greatly appreciated, and this information will significantly aid in diagnosing the problem and finding a potential solution. If you've tried any other troubleshooting steps not mentioned in your original post, please include those as well.

Once we have this information, we'll be better positioned to help resolve this issue. Thank you!
