### ISSUE TITLE
[Issue #4157] fix overflowing panel table headers

### ISSUE THREAD

**Issue by tonypowa** [moxious/triage#325]
Fixing [Issue #4157](https://github.com/grafana/grafana/issues/4157)

In consequence table's headers are not pinned and the text is folding but not overflowing.

**Comment by tonypowa** [comment]
This issue is a test copy of an issue in another repo.  Original issue: https://github.com/grafana/grafana/issues/#8441

**Comment by moxious** [comment]
Hello @tonypowa, thanks for your contribution! It seems like this issue is related to UI components within Grafana. This should likely be looked into by the team responsible for the **Frontend Platform project**. Could you please confirm if the overflowing table headers are part of the general Grafana UI or a specific plugin's UI? This will help us direct the issue to the appropriate team for a prompt resolution.

**Comment by moxious** [comment]
**Summary**: Issue #4157 is open, aiming to fix overflowing table headers in a panel, ensuring they are no longer pinned and the text wraps instead of overflowing.

**Comment by moxious** [comment]
**Elaboration**:


Hi @tonypowa, thank you for taking the time to submit an issue! 🌟 While you mentioned a fix for the table headers not being pinned and the text folding, we need a bit more information to fully understand and address the problem. Here are some additional details that would help us out: 

- Could you provide the **version** of Grafana you're working with?
- Is this issue present in the latest version or a specific branch?
- It would be beneficial to see a **screenshot** or a **video** of the issue for visual context.
- Can you describe the steps to **reproduce the issue** in detail, so we can see the behavior as you're experiencing it?
- Are there any **error messages** or **console logs** that you could share which appear when the issue occurs?
- Have you made any customizations to the CSS or configurations that might be affecting the table headers?

With these details, we'll be better equipped to assist you in fixing this issue. Looking forward to your response!
