### ISSUE TITLE
Dashboards: Newline symbols converted to space

### ISSUE THREAD

**Issue by tonypowa** [moxious/triage#329]
### What happened?

If a label value includes a newline symbol (`\n`), grafana fails to match it from dropdowns. It is instead converted to a space in some areas.

### What did you expect to happen?

From a UI design perspective, it makes sense to replace newline characters with white space in the legend and dropdown options, but for the data query, it should match.

![image](https://github.com/grafana/grafana/assets/52802566/d6a00ce7-98c8-447c-9f7d-53cdbb451140)

### Did this work before?

No.

### How do we reproduce it?

1. Push a metric with a label value ending in a newline character.

2. Use metric name as variable for a dropdown.

3. Use dropdown in query expression.

### Environment (with versions)?

Grafana: 9.5.3

### Grafana platform?

Kubernetes

### Datasource(s)?

Prometheus 2.49.1

**Comment by tonypowa** [comment]
This issue is a test copy of an issue in another repo.  Original issue: https://github.com/grafana/grafana/issues/#84687

**Comment by moxious** [comment]
Hello @tonypowa, thank you for reporting this issue. It seems closely related to the Dashboards functionality within Grafana. Therefore, I'm directing this issue to the **Dashboards Sharing Squad** project, as they handle aspects that include dashboard interactions with data sources and how certain characters or symbols are managed within dashboard visual components and queries. The team there should be able to assist further and determine if this requires a change in how newline symbols are handled or if it's behaving as intended. 

/tag Dashboards Sharing squad

**Comment by moxious** [comment]
**Elaboration**:


Hello @tonypowa, thank you for bringing this issue to our attention. We want to help you resolve this as quickly as possible, but we need a bit more information. Could you please provide the following details to help us diagnose the problem? 

- When you mention that Grafana fails to match it from dropdowns, could you clarify if there's an error message, or does it behave unexpectedly without any warning? If there's an error, a screenshot or the exact text would be really helpful.
- In the reproduction steps, could you specify what you mean by 'push a metric with a label value'? Are you referring to submitting a new metric through an API call or some other method? A snippet of the API call or the method used would be useful.
- Could you verify if the newline symbol is being preserved up until the point where it is expected to be matched in the dropdown and is not being stripped out earlier in the process?
- Are you noticing this issue consistently across different panels or queries or is it occurring under specific circumstances?
- If possible, could you provide the query expression you are using in step 3? This will help us understand if there's anything specific about the query that could be related to the issue.

Any additional context or examples of the issue would help expedite the troubleshooting process. If you've tried any workarounds or found any patterns in the behavior, that information could be valuable as well.

Thank you for your cooperation!
