### ISSUE TITLE
incorrect redirect when after creating if a new org in grafana

### ISSUE THREAD

**Issue by tonypowa** [moxious/triage#338]
### What happened?

after creating a new org and switch to a new org and from new back to the previous org i get this error in browser

<img width="1727" alt="Screenshot at Apr 13 15-24-29" src="https://github.com/grafana/grafana/assets/82488489/98ad3d6e-35ef-4ed4-ac17-e9f27d2f3aa5">

i don`t understand why i get incorrect redirect to 3000 port but other features works correct

### What did you expect to happen?

correct switch between orgs

### Did this work before?

no

### How do we reproduce it?

1. create a new org 

2. switch to a new org

3. switch back to previous org 

### Is the bug inside a dashboard panel?

no

### Environment (with versions)?

Grafana: docker.io/grafana/grafana:10.4.0

OS: Ubuntu 22.04.3 LTS (kubernetes workers)

Browser: google

### Grafana platform?

Kubernetes

**Comment by tonypowa** [comment]
This issue is a test copy of an issue in another repo.  Original issue: https://github.com/grafana/grafana/issues/#86088

**Comment by moxious** [comment]
Hi @tonypowa, it looks like you may be experiencing an issue with the Grafana UI when switching between organizations. This seems to be related to the **Frontend Platform** project as it deals with the user interface components of Grafana. I'll tag this accordingly to get the attention of the front end team.

```
/project Frontend Platform
```

In the meantime, can you provide any console logs from the browser developer tools that might show errors or failed network requests when the redirect issue occurs?

**Comment by moxious** [comment]
**Elaboration**:


### Request for Additional Information :mag:

Hi @tonypowa,

Thank you for reporting the issue with Grafana redirects! To help us understand and resolve the problem more efficiently, could you please provide the following information:

1. Could you provide detailed steps or conditions under which the redirection to port 3000 occurs? If it's random, any specific patterns noticed would be helpful.

2. Is there any reverse proxy or load balancer used in your environment that could be influencing the redirection behavior?

3. You've included an image link, but it seems to be broken. Can you please re-upload the screenshot directly to the GitHub issue or provide a working link? This visual context could be vital in understanding the issue.

4. Are there any relevant logs from the Grafana server or from your browser console that occur when the redirect problem happens? It would be great if you could share those as well.

5. Can you confirm if the issue persists across different browsers or if it's isolated to Google Chrome?

6. If possible, could you export and share the Grafana server configuration (omitting any sensitive information) that relates to organization management and redirects?

7. Lastly, have you made any custom configurations or are using any plugins that might be having an effect on this behavior?

Providing this additional information will give us a much clearer picture of the scenario and aid us in diagnosing the cause more accurately. Looking forward to your response!

All the best,
[Your Name]
