### ISSUE TITLE
Select: Fixes issue preserving search term (input) when selecting a value

### ISSUE THREAD

**Issue by tonypowa** [moxious/triage#342]
Fixes an issue with preserving the search query & filtering after selecting a value, even after doing the correct onInputChange implementation according to the react select docs it did not work as our middleware implementation did not take into account scenarios where we want to preserve the search query after selection and always cleared the "hasInputValue" state which sets filterOption to null which disabled search filtering.

Related to https://github.com/grafana/scenes/pull/709

**Comment by tonypowa** [comment]
This issue is a test copy of an issue in another repo.  Original issue: https://github.com/grafana/grafana/issues/#87013

**Comment by moxious** [comment]
**Summary**: This open issue describes a problem with maintaining the search query in a React select component after a value is selected, despite following the official documentation. The issue persists because the middleware implementation clears the search state, disabling the filter functionality.

**Comment by moxious** [comment]
Hello @tonypowa, thanks for the report. It seems that you're addressing an issue related to user interface component behavior, specifically preserving a search term. This sounds like it would be relevant to a frontend project that deals with UI components and search functionality. Based on the details provided, I believe the **Frontend Platform project** would be the best fit for this issue as it may involve updates to the frontend UI components or handling of input and search features within the Grafana platform.
