### ISSUE TITLE
Alert State History Not Working / Enabled

### ISSUE THREAD

**Issue by tonypowa** [moxious/triage#345]
### What happened?

As per this document attempting to setup alert history.

### What did you expect to happen?

Logs appear in Loki

### Did this work before?

No

### How do we reproduce it?

Configured as per - https://grafana.com/docs/grafana/latest/alerting/set-up/configure-alert-state-history/

```

 "feature_toggles": {

 "enable": "metricsSummary featureToggleAdminPage traceToMetrics alertStateHistoryLokiSecondary alertStateHistoryLokiPrimary alertStateHistoryLokiOnly"

 },

```

```

 "unified_alerting": {

 "admin_config_poll_interval": "60s",

 "alertmanager_config_poll_interval": "60s",

 "disable_jitter": "false",

 "disabled_orgs": "",

 "enabled": "true",

 "evaluation_timeout": "30s",

 "execute_alerts": "false",

 "ha_advertise_address": "",

 "ha_gossip_interval": "200ms",

 "ha_label": "",

 "ha_listen_address": "0.0.0.0:9094",

 "ha_peer_timeout": "15s",

 "ha_peers": "",

 "ha_push_pull_interval": "60s",

 "ha_redis_address": "",

 "ha_redis_db": "0",

 "ha_redis_max_conns": "5",

 "ha_redis_password": "",

 "ha_redis_peer_name": "",

 "ha_redis_prefix": "",

 "ha_redis_username": "",

 "max_attempts": "1",

 "max_state_save_concurrency": "1",

 "min_interval": "10s",

 "scheduler_tick_interval": "10s",

 "state_periodic_save_interval": "5m"

 },

 "unified_alerting.reserved_labels": {

 "disabled_labels": ""

 },

 "unified_alerting.screenshots": {

 "capture": "false",

 "capture_timeout": "10s",

 "max_concurrent_screenshots": "5",

 "upload_external_image_storage": "false"

 },

 "unified_alerting.state_history": {

 "backend": "loki",

 "enabled": "true",

 "loki_basic_auth_password": "",

 "loki_basic_auth_username": "",

 "loki_remote_read_url": "",

 "loki_remote_url": "https://loki.corp.mydomain.com",

 "loki_remote_write_url": "",

 "loki_tenant_id": "",

 "primary": "",

 "secondaries": ""

 },

```

This is using Mimir Alertmanager. No logs are being sent to my Loki instance.

### Is the bug inside a dashboard panel?

No 

### Environment (with versions)?

Grafana: 10.4.1

OS: Centos

Browser: Chrome

### Grafana platform?

Kubernetes

### Datasource(s)?

Mimir

**Comment by tonypowa** [comment]
This issue is a test copy of an issue in another repo.  Original issue: https://github.com/grafana/grafana/issues/#87162

**Comment by moxious** [comment]
**Summary**: User tonypowa is experiencing an issue where alert history logging is not working with Mimir and Loki on Grafana 10.4.1, despite configuration following the official documentation. The alert logs are not appearing in Loki as expected.

**Comment by moxious** [comment]
Hello @tonypowa, it seems like your issue is related to configuring the Alert State History features with Loki in Grafana. This would most likely fall under the **Alerting project**, as it pertains to the alerting functionality and its integration with a backend (Loki in this case) for storing alert history.

I recommend transferring this issue to the Alerting project for the right team to look into your configuration settings and assist further.

**Comment by moxious** [comment]
**Elaboration**:


Thank you for providing a detailed issue report, including your configuration settings and the environment in which you're experiencing the problem. To further assist you and to help us understand the issue more comprehensively, could you please provide the following additional information:

1. **Logs**: Could you share the relevant logs from Grafana after enabling the alert history feature?
 - This would typically include error logs or warning messages indicating why logs are not appearing in Loki.

2. **Loki Querying**: Have you tried querying Loki directly to check if there are any relevant logs stored?
 - If possible, provide a screenshot or the query and results that show your attempt to find the alert logs in Loki.

3. **Reproducibility**: Are there any specific alerts for which you expected to see logs in Loki but didn’t?
 - Details on specific scenarios can help isolate the issue.

4. **Network Configuration**: Is there any network policy or configuration that might be blocking communication between Grafana's alerting component and your Loki instance?
 - Information on network policies, firewalls, or any security measures that might affect connectivity.

5. **Loki Configuration**: Is your Loki instance configured correctly to receive logs from external sources like Grafana?
 - Reviewing the Loki configuration to ensure it's set up to accept incoming logs may help.

6. **Error Messages**: You mentioned that you're using Mimir Alertmanager. Are there any specific error messages or indicators in the Mimir logs that might point to an issue?

Once we have this information, we'll be in a better position to help troubleshoot the issue. Thank you for your cooperation!
