### ISSUE TITLE
allow_embedding not working on v11 preview

### ISSUE THREAD

**Issue by tonypowa** [moxious/triage#350]
### What happened?

allow_embedding not working on v11 preview. HTML in text

### What did you expect to happen?

render to html

### Did this work before?

?

### How do we reproduce it?

1. add a text 

2. add html like iframe

3. check if page get displayed

### Environment (with versions)?

Grafana:

OS:

Browser:

### Grafana platform?

A package manager (APT, YUM, BREW, etc.)

**Comment by tonypowa** [comment]
This issue is a test copy of an issue in another repo.  Original issue: https://github.com/grafana/grafana/issues/#87597

**Comment by moxious** [comment]
**Summary**: User tonypowa reported that the 'allow_embedding' feature is not functioning as expected in the v11 preview of Grafana, where HTML text is not being rendered properly into HTML. Steps to reproduce the issue include adding text with HTML content like an iframe to see if the page gets displayed. The circumstances or platform specifics under which it worked before, if at any time, are unclear.

**Comment by moxious** [comment]
**Elaboration**:


Thank you for reaching out and providing the details about the issue with allow_embedding in the v11 preview. To help us better understand and diagnose the problem, could you please provide some additional information? Here are a few questions and requests that would be very helpful to us:

- **Previous Functionality:** When you mention 'Did this work before?', could you clarify if you are referring to a previous version of Grafana where `allow_embedding` was working as expected? If so, which version was that?
- **Reproduction Steps:** The steps to reproduce the issue you provided are a good start, but could you also provide the exact HTML or iframe code snippet you're using that is not working, so we can replicate the issue on our end?
- **Screenshots or Screen Recordings:** If possible, could you include screenshots or a screen recording of the issue as it occurs?
- **Error Logs:** Are there any error messages in the Grafana server logs or in the browser's console when the issue happens? Those could provide valuable insight into what's going wrong.
- **Environment Details:** For the environment section, you've simply listed placeholders (Grafana:, OS:, Browser:). Could you provide the specific versions you are using? Knowing the exact version of Grafana, the operating system, and the browser can be critical for pinpointing the issue.
- **Plugin or Theme Customizations:** Are you using any plugins or custom themes that might be affecting the rendering of HTML content?
- **Content Security Policy (CPS) configurations:** Is there a particular Content Security Policy in place that might be preventing the embedding?

Once these additional details are provided, we'll be better positioned to help resolve the issue. Again, thank you for participating in the community and helping us improve our platform!

**Comment by moxious** [comment]
Thank you for the issue report, @tonypowa. It sounds like this could be related to the Backend platform project, considering the configuration nature of `allow_embedding`. However, to assist you better, could you please provide more specific information regarding the environment versions you're using, especially the Grafana version where you're experiencing this issue? Furthermore, is this regarding dashboard embedding or panel embedding? Any additional context would be greatly helpful for the team.
