### ISSUE TITLE
Dashboards: How to disable /api/search?

### ISSUE THREAD

**Issue by tonypowa** [moxious/triage#351]
### What happened?

Whenever the page is accessed, it automatically loads 

HTTP GET "/api/search?limit=5&dashboardUID=xxx&dashboardUID=yyy"

How can I avoid duplicate dashboardUID or disable it?

### What did you expect to happen?

avoid or disable it

### Did this work before?

No

### How do we reproduce it?

1.reload page, and use browser tools

### Environment (with versions)?

Grafana: 9.4.3

OS:windows/mac

Browser: Edge,chrome

### Grafana platform?

A downloaded binary

**Comment by tonypowa** [comment]
This issue is a test copy of an issue in another repo.  Original issue: https://github.com/grafana/grafana/issues/#87888

**Comment by moxious** [comment]
**Summary**: User 'tonypowa' reports an issue with the Grafana dashboard where an HTTP GET request to '/api/search' automatically includes duplicate 'dashboardUID' parameters. They are seeking a way to avoid these duplicates or disable the automatic search query upon page access. The issue remains open and occurs in Grafana version 9.4.3 on both Windows and Mac with Edge and Chrome browsers.

**Comment by moxious** [comment]
Hi @tonypowa, it seems your issue is related to dashboard interactions with Grafana's backend. This likely falls under the '**Dashboards Sharing squad**' project as they focus on features and issues associated with sharing and managing dashboards, which includes handling of dashboard-related API endpoints like `/api/search`. I recommend transferring this issue to that project to get the proper attention from the team specialized in this area.

**Comment by moxious** [comment]
**Elaboration**:


Hello @tonypowa,

Thank you for reaching out and reporting the issue you have encountered. To better assist you in resolving this matter, could you please provide a few additional details? Your initial description gives a good starting point, but I have some follow-up questions which could help in diagnosing the problem further:

1. Could you confirm if you have any custom plugins or scripts that might trigger the `/api/search` request multiple times? If so, please provide details or code snippets.

2. Are you seeing any errors or warnings in the Grafana server logs or in the console of your web browser's developer tools? If there are any, screenshots or logs could be very insightful.

3. How is your Grafana environment set up? Are there any specific settings in the `grafana.ini` file or environment variables that could be related to the search feature?

4. Did you make any changes to your dashboard or user permissions recently that might have affected the search functionality?

5. Could you share the request headers and response for the `/api/search` requests that are causing issues? Please make sure to redact any sensitive information before sharing.

6. It would be helpful if you could provide a more detailed step-by-step procedure of how to reproduce the issue starting from a clean state of Grafana, if possible.

Any additional context around the problem, such as the frequency of occurrence, whether it impacts the functionality or performance, and any temporary workarounds you have discovered, will also be valuable.

We appreciate your contribution to making Grafana better and looking forward to your response to address the issue effectively.

Best regards,
The Grafana Team
