### ISSUE TITLE
Alert List panel plugin message twitching side-to-side on data refresh

### ISSUE THREAD

**Issue by tonypowa** [moxious/triage#352]
### What happened?

I have found that the Alert List panel plugin twitches when data is refreshed. It is much more noticeable and annoying when the refresh rate is high. I noticed in the code there is mention of something related:

https://github.com/grafana/grafana/blob/37d1d1c0a0edc43e0443874337c6a78eafe8414d/public/app/plugins/panel/alertlist/UnifiedAlertList.tsx#L252

But, it does not seem to work for me. It seems like the vertical scrollbar pops up for a few milliseconds and that shifts the message to the left.

Similar behaviour happens when there are alerts and the panel is being refreshed. I have attached a short video to show what I observe. I am using the latest Grafana version 11.0.0

https://github.com/grafana/grafana/assets/79968074/c9dcda45-c194-4f95-bcb3-32dd765680e1

### What did you expect to happen?

 "No alerts matching filters" should not jump to the left every time data is refreshed.

### Did this work before?

Don't know, I am first time Grafana user.

### How do we reproduce it?

Create an empty dashboard and add an empty alert panel plugin component to the dashboard. Increase the refresh rate of the dashboard to amplify the effect. You will notice that the "No alerts matching filters" jump to the left every time data is refreshed.

### Is the bug inside a dashboard panel?

Yes

### Environment (with versions)?

Grafana: 11.0.0

OS: Ubuntu 20.04

Browser: Chrome (latest)

### Grafana platform?

Docker

### Datasource(s)?

Prometheus

**Comment by tonypowa** [comment]
This issue is a test copy of an issue in another repo.  Original issue: https://github.com/grafana/grafana/issues/#87894

**Comment by moxious** [comment]
**Summary**: The Alert List panel plugin in Grafana 11.0.0 exhibits a glitch where the message 'No alerts matching filters' moves side-to-side during data refreshes, especially at high refresh rates. The issue, which appears to be related to the vertical scrollbar briefly appearing, is replicable on a dashboard with an empty alert panel plugin and happens in a Docker environment with Prometheus as the datasource.

**Comment by moxious** [comment]
**Elaboration**:


Hello @tonypowa, thank you for bringing this issue to our attention!

While the video you've attached is instrumental in understanding the twitching effect you're experiencing, there are a couple of additional details that would help us diagnose the problem further:

1. **Browser Details:** Could you please provide the specific version of Chrome you are using? Occasionally, issues can be browser-specific.

2. **Console Logs:** Are there any error messages or warnings in the browser's Developer Console that appear related to this issue when the twitching occurs? To check, right-click on the page, select 'Inspect', go to the 'Console' tab, and then observe if any messages are logged when you refresh.

3. **Network Activity:** Monitoring the Network tab in Chrome's Developer Tools during a refresh may provide insights into what is occurring when the panel is redrawn. Could you provide any relevant network requests that seem to correlate with the twitching?

4. **Dashboard Configuration:** Are you able to share the JSON of the dashboard configuration? This could help us replicate the exact setup you are using.

5. **Screenshots or Screen Recording:** If the link to the short video isn't working, could you please verify the link or provide it some other way, such as attaching it as a file to the GitHub issue?

6. **Scrollbar Appearance:** You've mentioned that the scrollbar appears briefly, causing the content to shift. Are there any custom CSS styles applied on the Grafana instance that might be affecting the default styling of scrollbars?

Feel free to share any additional details or observations that you think might be relevant. Once we have this information, we'll be in a much better position to investigate the issue and get to the bottom of it.

Kind regards,
The Support Team

**Comment by moxious** [comment]
Hi @tonypowa, thanks for reporting the issue with the Alert List panel plugin. Since this is related to the plugin's behavior, it seems like it would best fit under the **Plugins Platform** project. The team responsible for plugin architecture and related concerns can investigate this visual glitch during data refreshes. 

_I have forwarded this issue to the Plugins Platform project for further review._
