### ISSUE TITLE
Data cleared for MQTT source when dashboard updates

### ISSUE THREAD

**Issue by tonypowa** [moxious/triage#356]
### What happened?

When you have both a panel with a live MQTT data source and a DB query, every time the dashboard refreshes, it deletes any data from the live panel as well. This means the live panel will reset to empty every time the dashboard updates. (every 5, 10, 30 seconds or whatever)

### What did you expect to happen?

Not lose data from live panels when the dashboard gets now data from other panels.

### Did this work before?

Never seen it work 

### How do we reproduce it?

1. Add a live panel to a dashboard

2. Set "Set auto refresh interval" to some valie

3. Wait for the interval

### Is the bug inside a dashboard panel?

No, dashboard itself. 

### Environment (with versions)?

Grafana: Grafana v10.4.1 (d94d597d84)

OS: MacOS 13.2.1

Browser: Safari 16.3 / Chrome / FireFox

### Grafana platform?

Kubernetes

### Datasource(s)?

MQTT 1.0.0-beta.4

**Comment by tonypowa** [comment]
This issue is a test copy of an issue in another repo.  Original issue: https://github.com/grafana/grafana/issues/#88038

**Comment by moxious** [comment]
**Elaboration**:


Hello @tonypowa,

Thank you for bringing this issue to our attention. To help us investigate the problem with the MQTT data source on the dashboard effectively, could you please provide a bit more information?

1. **Configuration Details**: Could you share the configuration settings for the MQTT data source and the panel you're experiencing this issue with? If there are any specific settings that are required to reproduce this issue, including them would be helpful.

2. **Logs**: Are there any logs from Grafana or the MQTT broker that indicate an error or unexpected behavior during the auto-refresh interval? If so, please include them.

3. **Reproduction Steps**: It's crucial to ensure the steps to reproduce the issue are correct and complete. When you mention _'Set

**Comment by moxious** [comment]
Hi @tonypowa, it sounds like you might be encountering an issue related to the MQTT datasource in Grafana. To ensure that the right team can help you with this issue, I suggest moving this to the **Plugins Platform** project, as that team focuses on the integrations and extensions like datasources for Grafana. 

```markdown
/transfer to Plugins Platform
```

**Comment by moxious** [comment]
**Summary**: Issue #356 is OPEN, where the author reports that any live data from MQTT sources on a Grafana dashboard is cleared upon dashboard refresh, contrary to the expectation that live panel data should persist. This issue persists across browsers and platforms, and reproducible steps are provided.

**Comment by tonypowa** [comment]
> /transfer to Plugins Platform 

app platform
