### ISSUE TITLE
Nested Pie/Donut Charts 

### ISSUE THREAD

**Issue by tonypowa** [moxious/triage#358]
### What happened?

I am working with google sheets as my datasource (query A & B) and I am trying to implement a donut with 2 layers (inner and outer layers). 

![1](https://github.com/grafana/grafana/assets/139092406/348cdc64-a7f4-46ce-b749-1a3f337f4619)

![2](https://github.com/grafana/grafana/assets/139092406/4b0bbff1-1e3c-4606-944d-20b29f8571d1)

### What did you expect to happen?

Right now I am able to create a donut chart but i want my query B to be in the inner donut chart.

### Did this work before?

No

### How do we reproduce it?

1. It is pretty straightforward, just some data in google sheets

2.

3.

### Environment (with versions)?

Grafana:

OS:

Browser:

### Grafana platform?

None

**Comment by tonypowa** [comment]
This issue is a test copy of an issue in another repo.  Original issue: https://github.com/grafana/grafana/issues/#88096

**Comment by moxious** [comment]
Hi @tonypowa, it seems like you're looking to implement a feature related to data visualization in Grafana. Based on your description, the most relevant project for this issue would be the *DataViz project*, as it pertains to the development of visualization capabilities such as nested pie/donut charts within Grafana.

**Comment by moxious** [comment]
**Summary**: User tonypowa opened an open issue regarding the inability to create a nested two-layer donut chart in Grafana, with the inner layer to represent data from Query B, using Google Sheets as the data source. This feature has not worked before and they are seeking assistance to achieve this visualization.

**Comment by moxious** [comment]
**Elaboration**:


Thank you for raising this issue, Tony. To better understand and address the problem you're facing with nested pie/donut charts, we'll need a bit more detailed information. Could you please provide the following details? 

- Can you provide a sample of the data structure in your Google Sheets that you're using for both queries (A & B)?
- Can you describe a little more about how your queries are structured and how you are currently generating the donut chart with just Query A?
- Are there any specific settings or configurations you've attempted when trying to add Query B to the inner donut chart?
- Regarding the reproduction steps, could you please detail each step that someone would need to perform to replicate the issue from scratch? Explicit steps can help us understand where things might be going wrong.
- Have you found any documentation or forums that suggest nested donut charts are supported in the version of Grafana you are using?
- Could you also provide the exact versions of Grafana, the Operating System (OS), and the Browser where you are experiencing this issue?
- Lastly, it seems the image links you've provided are not working. Can you check the links and provide updated ones? If you prefer, you could also describe in text what we are meant to see in those images.

Once we have this information, we'll be in much better shape to find a solution. Thank you!
