### ISSUE TITLE
Cloud Monitoring PromQL: Alias By not showing in query panel

### ISSUE THREAD

**Issue by tonypowa** [moxious/triage#361]
### What happened?

When using PromQL instead of of builder with the GCP Cloud monitoring datasource the Alias By box is not showing.

### What did you expect to happen?

The Alias by box showing up in the panel

### Did this work before?

N/A

### How do we reproduce it?

1. Open "explore"

2. Use a cloud monitoring datasource and switch to PromQL instead of builder

3. The "Alias by" is not shown

### Environment (with versions)?

Grafana: 10.4.1

OS: MacOS 14.1.2

Browser: Chrome 124

### Grafana platform?

Kubernetes

### Datasource(s)?

Google Cloud Monitoring

**Comment by tonypowa** [comment]
This issue is a test copy of an issue in another repo.  Original issue: https://github.com/grafana/grafana/issues/#88173

**Comment by moxious** [comment]
**Summary**: The issue reported by tonypowa on GitHub is about the 'Alias By' box not appearing in the query panel when using PromQL with the GCP Cloud Monitoring datasource in Grafana version 10.4.1.

**Comment by moxious** [comment]
Hello @tonypowa, thank you for reporting this issue. It seems related to an interaction of the Explore feature with the Google Cloud Monitoring datasource. I would recommend transferring this issue to the **Explore project**, where the team responsible for the Explore functionality of Grafana can further investigate the absence of the 'Alias By' box when using PromQL with the GCP Cloud Monitoring datasource.

**Comment by moxious** [comment]
**Elaboration**:


Thank you for reporting this issue, tonypowa. To help us better understand and replicate the problem you're experiencing with the Alias By functionality in Grafana's PromQL, could you please provide us with the following additional information? This will greatly assist in diagnosing the issue.

1. Has the Alias By box previously appeared for you in similar conditions, or is this the first time you've encountered this problem?
2. Could you provide a screenshot showing where you expect the Alias By box to be and its absence? This visual context can often be very helpful.
3. Are there any console errors in the browser when trying to use the PromQL feature where the Alias By box is not shown? You can check this by opening the developer tools in Chrome (with F12 or Cmd+Opt+I on MacOS) and navigating to the 'Console' tab.
4. Have you tried different browsers or incognito mode to see if the issue persists there as well?
5. Are there any relevant logs from Grafana that could provide additional insights? You might need to set the logging level to debug to get detailed messages.
6. Is this issue occurring for all queries in PromQL mode or only specific ones? If it's specific, please share an example of a query that should have 'Alias By' but does not.

Once we have this information, we'll be in a better position to help resolve your issue. Thank respectively for your collaboration!
