### ISSUE TITLE
Grafana does not restart after upgrade.

### ISSUE THREAD

**Issue by tonypowa** [moxious/triage#370]
### What happened?

After an upgrade from Grafana 10 to 11 (on Ubuntu 20.04.4), grafana server does not start.

`sudo -u grafana /usr/share/grafana/bin/grafana server --config /etc/grafana/grafana.ini`

is working but

`sudo systemctl restart grafana-server.service `

does not complete.

```

sudo systemctl status grafana-server.service 

○ grafana-server.service - Grafana instance

 Loaded: loaded (/lib/systemd/system/grafana-server.service; enabled; vendor preset: enabled)

 Active: inactive (dead)

 Docs: http://docs.grafana.org

```

I added debug logs in the ini file but nothing is showing up. I do not use SSH in this configuration, it is proxied by nginx.

It works well if started via the sudo line above.

Ideas?

### What did you expect to happen?

I expect Grafana to start :)

### Did this work before?

Yes

### How do we reproduce it?

1.

2.

3.

### Is the bug inside a dashboard panel?

No

### Environment (with versions)?

Grafana: 11

OS: ubuntu 20.04.4

Browser: all

### Grafana platform?

APT

**Comment by tonypowa** [comment]
This issue is a test copy of an issue in another repo.  Original issue: https://github.com/grafana/grafana/issues/#88962

**Comment by moxious** [comment]
**Summary**: Issue 370 remains OPEN; Grafana server fails to restart after an upgrade from version 10 to 11 on Ubuntu 20.04.4 using systemd, despite working when started directly with a command. The author is seeking ideas for resolution.

**Comment by moxious** [comment]
**Elaboration**:


Thank you for reaching out, @tonypowa, and for providing the initial details of your issue with upgrading Grafana. To help us investigate this further, a few additional pieces of information would be useful. When you have a chance, could you provide the following details?

- Can you share the output of the `journalctl -u grafana-server.service` command after attempting to restart the service with `systemctl`? This may contain logs that are not captured in the Grafana debug logs.
- Have you checked the permissions of the Grafana directories and configuration files to ensure that the Grafana user can access them?
- Are there any relevant messages in the syslog (`/var/log/syslog`) related to the service start attempt?
- Did you follow any specific upgrade guide or steps that you can outline, which might highlight a missed step or known issue?
- In case there are environment-specific issues, can you confirm if there were any significant changes to your system configuration, packages, or network settings between the working version and the upgrade?
- Can you include the contents of your `grafana-server.service` file? Sometimes custom modifications can lead to service start issues.

Once you provide the above information, we should be in a better position to understand and resolve the issue. Thanks for your cooperation!

**Comment by moxious** [comment]
Hello @tonypowa, it sounds like this might be an issue related to the Grafana server itself, possibly after an upgrade process. I'm going to direct this to the **Backend platform project** team as they are best equipped to handle server start-up issues. Before they look into this, please ensure that you've checked the permissions and ownership of the files in `/etc/grafana` and `/var/lib/grafana`, as incorrect permissions can sometimes cause the service to fail to start. It can also be helpful to inspect the journal logs using `sudo journalctl -u grafana-server.service` to get more detailed error messages, if any.

Please add any additional logs or error messages to this issue to aid in troubleshooting.

/assign @backend-platform
