### ISSUE TITLE
Relative Time: Issue When Browser and Computer Time Settings Differ

### ISSUE THREAD

**Issue by tonypowa** [moxious/triage#371]
### What happened?

**Working Configuration:**

Data Timestamp: UTC

Browser Time Settings: UTC+2

Computer Time Settings: UTC+2

Selected Timezone in Grafana: Any timezone

Behavior: Filtering by "Last 30 Minutes" correctly displays the real last 30 minutes.

**Non-Working Configuration:**

Data Timestamp: UTC

Browser Time Settings: UTC+2

Computer Time Settings: UTC+5 (UTC+5 is an example. This could be any time different to browser Time)

Selected Timezone in Grafana: Any timezone

Issue: When filtering by Time Range "Last 30 Minutes", no data is displayed. It appears to filter by what is considered "future" last 30 minutes.

**Possible Bug:** 

The time range filter seems to malfunction under differing browser and computer time settings, leading to incorrect data filtering that assumes a future time range.

### What did you expect to happen?

We expect to see the real last 30 minutes of data, regardless of the browser or computer time settings.

### Did this work before?

No

### How do we reproduce it?

1. First, check the computer Time is the same as the browser.

2. If it is the same, create a dashboard including a Time Series Panel showing data for the last 30 minutes. Capture this image.

3. Change the computer Time to be different from the Browser.

4. Go to the previous dashboard and capture the image.

5. Both images will probably show different Time ranges when they should always show the last real 30 minutes.

### Is the bug inside a dashboard panel?

No

### Environment (with versions)?

Grafana: 10.0.3

OS:

Browser:

### Grafana platform?

None

**Comment by tonypowa** [comment]
This issue is a test copy of an issue in another repo.  Original issue: https://github.com/grafana/grafana/issues/#89137

**Comment by moxious** [comment]
**Summary**: Issue #371 is OPEN: A time range filter bug occurs in Grafana when computer and browser time settings differ, e.g., UTC+5 vs. UTC+2, causing the 'Last 30 Minutes' filter to display no data as it inaccurately assumes a future time range instead of the actual last 30 minutes.

**Comment by moxious** [comment]
Hello @tonypowa, thanks for the detailed report. Based on your description, the issue seems to be related to the usage and parsing of time settings. It appears closely related to timezones and how they are handled, potentially within the Grafana backend, as it involves data filtering and timestamp processing. I suggest associating this issue with the **Grafana Metrics project**, which seems most relevant given the context of time series and data filtering:
```markdown
@grafana-metrics-team Could you please take a look at this reported issue with relative time filters and differing time settings between the browser and the computer? Users are experiencing issues with displaying data correctly for 'Last 30 Minutes' due to this discrepancy.
```

**Comment by moxious** [comment]
**Elaboration**:


Hi @tonypowa, 

Thank you for taking the time to report this issue. You've done a good job describing the behavior you're encountering with the relative time filters in Grafana when the browser and computer have differing time settings.

To help us understand and replicate the issue further, could you please provide the following details:

1. **OS Details**: Could you specify the operating system you're using along with its version? (e.

2. **Browser Details**: Which browser(s) have you encountered this issue with? Please include version numbers if possible.

3. **Datasource Details**: What datasources are you using? Knowing the specific data sources may help in reproducing the issue, as some might handle time data differently.

4. **Grafana Settings**: Are there any specific Grafana settings that you have configured which might affect timezone handling?

5. **Screenshots or Screen Recordings**: If possible, could you attach screenshots or a screen recording showing the issue in action? This often helps to clearly see what is happening.

6. **Error logs**: Are there any error logs in the Grafana server or the browser's developer console when the problem occurs?

7. **Reproduction on a Different Setup**: Have you tried reproducing this issue on a different machine or browser to rule out specific local configuration issues?

This additional information will greatly assist our investigation into the issue.

Thank you again, and we look forward to getting to the bottom of this!

Kind regards,

[Your Name]
[Your Role]
