### ISSUE TITLE
psql: Upgrade from v10.2 to v10.4 fails over unique index creation

### ISSUE THREAD

**Issue by tonypowa** [moxious/triage#373]
### What happened?

Upgrade to v10.4 from v10.2 failed with migration error:

```

logger=sqlstore t=2024-06-13T11:01:35.055802348Z level=info msg="Connecting to DB" dbtype=postgres

logger=migrator t=2024-06-13T11:01:35.077497999Z level=info msg="Starting DB migrations"

logger=migrator t=2024-06-13T11:01:35.104943582Z level=info msg="Executing migration" id="Add unique index user_uid"

logger=migrator t=2024-06-13T11:01:35.117831431Z level=error msg="Executing migration failed" id="Add unique index user_uid" error="pq: could not create unique index \"UQE_user_uid\"" duration=12.886056ms

logger=migrator t=2024-06-13T11:01:35.117866136Z level=error msg="Exec failed" error="pq: could not create unique index \"UQE_user_uid\"" sql="CREATE UNIQUE INDEX \"UQE_user_uid\" ON \"user\" (\"uid\");"

Error: ✗ migration failed (id = Add unique index user_uid): pq: current transaction is aborted, commands ignored until end of transaction block

```

After a rollback everything was still fine, so no permanent damage.

### What did you expect to happen?

Ideally the migration would check that the UIDs are unique before trying to create a unique index.

### Did this work before?

N/A (this is the first time the migration is applied)

### How do we reproduce it?

1. (create non-unique users with the same email address with different case?)

2. (some db settings?)

3. Upgrade from 10.2 to 10.4

### Is the bug inside a dashboard panel?

No

### Environment (with versions)?

Starting point is

```

 Image: docker.io/grafana/grafana:10.2.3

 Image ID: docker.io/grafana/grafana@sha256:6b5b37eb35bbf30e7f64bd7f0fd41c0a5b7637f65d3bf93223b04a192b8bf3e2

```

### Grafana platform?

Kubernetes

**Comment by tonypowa** [comment]
This issue is a test copy of an issue in another repo.  Original issue: https://github.com/grafana/grafana/issues/#89159

**Comment by moxious** [comment]
Hello @tonypowa, this issue appears to be related to a database migration process within Grafana. Since it's about an upgrade failing and interaction with the database, the best fit for this issue seems to be the **Backend platform project**.

However, if the problem is primarily concerning the application deployment via Kubernetes, the **Grafana Operator Experience Squad** may also be relevant. If you believe this migration issue has more to do with the Operator or Kubernetes deployment process, please clarify so we can triage it to the right team.

Would you be able to provide a bit more detail on your database configuration prior to the upgrade attempt, specifically if there are any unique constraints or case sensitivity configurations set in PostgreSQL? This will help the team to better understand the issue and resolve the migration error.

**Comment by moxious** [comment]
**Summary**: Users are experiencing a migration error when upgrading from psql v10.2 to v10.4 related to the creation of a unique index. The process fails and suggests a need for a pre-migration check to ensure UID uniqueness. No permanent damage occurs due to a successful rollback.

**Comment by moxious** [comment]
**Elaboration**:


Hi @tonypowa, thank you for bringing this issue to our attention. To assist you better and address the migration error you encountered, we need some additional information. Could you please provide the following details?

1. Can you confirm that the `uid` field in the `user` table indeed contains non-unique values? It would be helpful to know if there are any duplicate uids present before the migration.
2. Are there any specific steps you took before the upgrade that might have affected the uniqueness of the `uid` fields, such as manual database modifications or scripts?
3. Please provide the exact steps that can reproduce this issue, including any specific database settings or states necessary to trigger the problem. The details provided in step #1 and #2 under 'How do we reproduce it?' are a bit unclear.
4. Could you share any relevant parts of your Grafana logs or Postgres logs that might show errors related to the UIDs or the migration process?
5. If possible, please execute the following SQL query and share the results: `SELECT uid, COUNT(*) FROM user GROUP BY uid HAVING COUNT(*) > 1;` This will help determine if there are any duplicate uids.

Once we have this information, we'll have a better understanding of the cause of the issue and can work towards a solution. Thank you for your cooperation!
