### ISSUE TITLE
Every time I access my linux dashboard, it's telling me to migrate from Angular, which I do. Over and over and over and over again

### ISSUE THREAD

**Issue by tonypowa** [moxious/triage#377]
### What happened?

Every time I access my linux dashboard, it's telling me to migrate from Angular, which I do. Over and over and over and over again

### What did you expect to happen?

I expected the migration from angular to be a one time occurrence.

### Did this work before?

It worked before Angular was deprecated.

### How do we reproduce it?

1. log on to grafana

2. navigate to my linux dashboard

3. Read the warning about angular, hit the migrate button, 

4. EVERY TIME I VIEW THE DASHBOARD

### Environment (with versions)?

Grafana: cloud

OS:

Browser:

### Grafana platform?

I use Grafana Cloud

### Datasource(s)?

prometheus

**Comment by tonypowa** [comment]
This issue is a test copy of an issue in another repo.  Original issue: https://github.com/grafana/grafana/issues/#89697

**Comment by moxious** [comment]
**Summary**: User 'tonypowa' is experiencing an issue where they are prompted to migrate from Angular every time they access their Linux dashboard on Grafana Cloud, despite completing the migration process multiple times. The problem persists even after the initial deprecation of Angular.

**Comment by moxious** [comment]
**Elaboration**:


Hello @tonypowa, thank you for bringing this issue to our attention! It's important that we resolve repetitive migration prompts to improve your experience. To get a clearer picture of what's happening, I have a few questions that will help us diagnose this issue further: 

- After you perform the migration by clicking the migrate button, does the dashboard appear to operate correctly until you navigate away and return?
- Can you check if there are any errors in the browser console after you attempt the migration?
- Have you tried clearing your browser cache or using a different browser to see if the issue persists?
- Does the same issue occur for other dashboards that require migration or is it specific to your 'linux dashboard'?
- Could you describe the versions of Grafana Cloud that you're using and the version from which you're attempting to migrate?
- Are there any custom plugins or scripts running on your dashboard that might interfere with the migration process?
- Can you provide a screenshot of the migration prompt and any related messages that appear on your dashboard?
- If possible, would you be willing to share the dashboard JSON (with sensitive information redacted) so we can try to replicate the issue?

Thank you for working with us to get to the bottom of this!

**Comment by moxious** [comment]
Hi @tonypowa, it seems like you are experiencing issues related to the frontend of Grafana, particularly the migration process from Angular panels after updates. This looks like a perfect match for the **Frontend Platform project** as it concerns the frontend user interface and migration mechanisms.

To help the team diagnose and address this issue, could you please provide more detailed logs or error messages if available after attempting the migration?

Thanks for reporting this, and I'll make sure the Frontpanel Platform team is aware of this migration loop issue.
