### ISSUE TITLE
Alerting: Image renderer screenshots cannot be used in custom templates

### ISSUE THREAD

**Issue by tonypowa** [moxious/triage#380]
### What happened?

Using a custom alerting notification template for E-mail does not include image renderer screenshots

Example default template output: 

![image](https://github.com/grafana/grafana/assets/92876786/41d86b76-013f-4fe4-b3bf-617f7a663734)

Example custom template output: 

![image](https://github.com/grafana/grafana/assets/92876786/037f4f8c-1767-458d-9fb7-1db7133e3efe)

### What did you expect to happen?

Alert emails include panel screenshots

### Did this work before?

No

### How do we reproduce it?

1. Set up image renderer as a separate docker container

2. Create custom alert template

3. Create an alert panel and trigger an alert

### Environment (with versions)?

Grafana: v10.3.3

On K8s

### Grafana platform?

Kubernetes

**Comment by tonypowa** [comment]
This issue is a test copy of an issue in another repo.  Original issue: https://github.com/grafana/grafana/issues/#89874

**Comment by moxious** [comment]
**Summary**: The issue on GitHub number 380, opened by tonypowa, reports that screenshots from the image renderer are missing in custom alerting notification templates for emails in Grafana v10.3.3 on Kubernetes, while they work with default templates.

**Comment by moxious** [comment]
Hello @tonypowa, it seems your issue is related to the Alerting mechanisms within Grafana. I will forward this to the **Alerting project** team as it appears to be the most relevant for handling Alerting templates and image rendering issues. They will be able to provide you with further assistance.
