### ISSUE TITLE
Delay in keyboard shortcuts ( v11.0 or newer only)

### ISSUE THREAD

**Issue by tonypowa** [moxious/triage#382]
,

**Comment by tonypowa** [comment]
This issue is a test copy of an issue in another repo.  Original issue: https://github.com/grafana/grafana/issues/90020

**Comment by moxious** [comment]
**Summary**: User 'tonypowa' reports a delay in the 'e' keyboard shortcut for editing panels in Grafana v11.1.0, which results in editing the wrong panel. The issue was not present before upgrading to v11 and occurs in both Chrome and Firefox on Windows 11.
