### ISSUE TITLE
Loki: Filter for value in query shows empty results

### ISSUE THREAD

**Issue by tonypowa** [moxious/triage#384]
### What happened?

When I try to filter for value in query (with the small icon in the field), it shows "No logs found." I'm not sure if I'm missing something, but I think it may be a bug, because we would even have problems with derived fields which we apparently don't have (according attached screenshots)

![obrazek](https://github.com/grafana/grafana/assets/138204173/cccee499-e61b-4092-b664-6cad0d614387)

![obrazek](https://github.com/grafana/grafana/assets/138204173/46d078d0-08ee-4ba4-a239-08d7f10d40bb)

### What did you expect to happen?

When I click the small + icon for value filter, it should filter all the records with that value. For example:

Domain contains domain.xyz, then I should get only records that contains domain.xyz in Domain field.

![obrazek](https://github.com/grafana/grafana/assets/138204173/2f05c57b-b167-46cb-8f96-50cedef26eec)

### Did this work before?

Unfortunately I'm not sure, because we didn't use it before.

### How do we reproduce it?

1. Define derived field in the datasource

2. Verify the derived field is shown in your records in the "Explore" tab.

3. Try to filter for any value from your derived field

4. You should see No logs found.

### Environment (with versions)?

Grafana: Grafana v11.1.0 (5b85c4c2fc)

OS: Rocky Linux 9.4 (Blue Onyx)

Browser: Firefox 127.0.2

### Grafana platform?

Docker

### Datasource(s)?

Loki 2.9.8

**Comment by tonypowa** [comment]
This issue is a test copy of an issue in another repo.  Original issue: https://github.com/grafana/grafana/issues/#90052

**Comment by moxious** [comment]
**Summary**: The issue reports a potential bug in Grafana where filtering for a value within a Loki datasource query results in 'No logs found,' even when corresponding records exist. The user expects filtered results to show relevant records with the specified value, but instead encounters empty results. Steps for reproduction and the environment details are provided.

**Comment by moxious** [comment]
Hello @tonypowa, thanks for reporting the issue with Loki. Based on the details you've provided, it seems like this issue would best fit within the **Observability Logs Project** domain, as it's related to log filtering and derived fields in the Loki datasource. I will label this issue accordingly so that the appropriate team can take a look at it.

**Comment by moxious** [comment]
**Elaboration**:


Thank you for submitting an issue report and including screenshots to detail the problem you're encountering with Loki filtering in Grafana. To ensure our developers and contributors can effectively investigate this further, we'd require some additional information. Could you please provide the following details? 

- Could you confirm if there are any error messages in the Grafana server logs or within the browser console when the issue occurs?
- Would it be possible for you to share a redacted query that you used when this issue happened? This can sometimes provide insight into the problem.
- Have you attempted to reproduce this issue with a different browser or an incognito/private window to rule out any browser extensions or cache-related problems?
- Regarding the 'No logs found' message, are there any steps or filters that you might have skipped before this issue appeared?

To better understand the context:
- Are there any specific pattern or type of log entry that seems to trigger this issue when filtered, or does it happen with all entries?
- In addition to the derived fields, are there any other custom configurations applied to your Loki datasource that we should be aware of?

Additionally, if you have access to the Loki logs, checking there for any related error messages during the attempt to filter the queries might help in debugging the issue.

Once we have this information, it will help us to diagnose the issue with greater accuracy. Thank you again for reaching out, and we look forward to resolving this for you!
