### ISSUE TITLE
BUG: Invalid numeric when delete dashboard

### ISSUE THREAD

**Issue by tonypowa** [moxious/triage#389]
### What happened?

Dashboards: have error when I delete dashboard

<img width="760" alt="lQLPJwmvIWqo41_NA1PNBfCwoMv-PA6PIfwGfvHR5ZWWAA_1520_851" src="https://github.com/user-attachments/assets/958a579a-0226-4b57-be47-423dc2f9322b">

### What did you expect to happen?

should delete success

### Did this work before?

if we have no data in playlist, it will work

this case caused by playlist_item table, value column type, since dashboard.id is a int64 data

### How do we reproduce it?

1. have a playlist , playlist_item should have data

2. MYSQL SQLMODE: STRICT_ALL_TABLES

3. delete one dashboard

### Is the bug inside a dashboard panel?

yes.

I lookinto the source code, and found we will have a PS when we delete dashboard

<img width="237" alt="C56A716F-1A6C-4866-8C86-8F715B62DAEE" src="https://github.com/user-attachments/assets/b1cdfe9a-e498-4344-8283-03ec594131b5">

and we will have playlist_item in it, but value in playlist is not bigint type, mysql will not convert int to text in strict mode

### Environment (with versions)?

Grafana:

OS:

Browser:

### Grafana platform?

None

**Comment by tonypowa** [comment]
This issue is a test copy of an issue in another repo.  Original issue: https://github.com/grafana/grafana/issues/#90457

**Comment by moxious** [comment]
**Summary**: The issue describes a bug where attempting to delete a dashboard when there is data in the playlist_item table fails due to a mismatch between the expected int64 data type and the actual data type in strict SQL mode. The bug is opened by user tonypowa and is still in the OPEN state.

**Comment by moxious** [comment]
Hello @tonypowa, it seems like this issue pertains to the functionality of the Dashboards in Grafana. Based on the details you've provided—specifically regarding the deletion of a dashboard and its relation to the playlist_item table and dashboard panel—the **Dashboards Sharing squad** project seems to be the most relevant team to investigate this bug. I'll label this issue accordingly to ensure it reaches the right team.

**Comment by moxious** [comment]
**Elaboration**:


Hello @tonypowa, and thank you for reporting this issue. I'd like to gather a bit more information to help us understand and reproduce the issue effectively. Could you please provide the following details?

- **Grafana version:** Could you specify the exact version of Grafana you are using?
- **Operating System:** What OS is the Grafana instance running on?
- **Browser details:** Which browser and version are you experiencing this issue in?
- **Error logs:** Are there any error messages in the Grafana logs or browser console when the issue occurs?
- **Step-by-step reproduction:** You provided some steps to reproduce the issue, but it would be beneficial if you could expand on those steps a bit more. Could you provide a more detailed list of steps or a minimal reproducible example?
- **Screenshot clarity:** The provided screenshots are helpful, but they appear to have been cut off. Could you provide the complete screenshot or any additional screenshots that show the full error message or context?

This additional information will help us pinpoint the issue and work towards a resolution. Thank you for your collaboration!

---
**Note for the maintainers:** This issue might be related to type conversion problems with MySQL in strict mode, potentially requiring a schema migration or code adjustment for type compatibility.
